import { IPetMap } from '../interfaces/pet.interface';

export const DOGS_MAP: IPetMap = {
  teddyDog: {
    details: {
      overview:
        '<p>泰迪狗小巧、毛茸茸、迷人，让人一见钟情。</p><p>这些玩具小狗快乐、顽皮、可爱。</p><p>他们喜欢用可爱的行动，给主人留下美好回忆，让他们的人类家庭幸福。</p><p>泰迪狗热衷于各类家庭活动，非常喜欢游戏、拥抱和训练。</p><p>泰迪熊狗，也被称为 Zuchon 或 Shichon，是一种设计师犬种。</p><p>通常是“西施犬”与“比熊犬”的杂交，或者是西施犬与马耳他犬杂交的后代。</p><p>它们体型娇小，毛茸茸的，脸型圆润可爱，外观上很像泰迪熊。</p>',
      characteristics:
        '<p>泰迪狗非常友善——它们对孩子、其他宠物和陌生人都很友善。</p><p>泰迪狗不会偏爱，他是一种魅力十足的狗，对每个人都一视同仁，是儿童和成人最美妙的伴侣宠物。</p><p>可爱又温暖，是一种优秀的治疗犬。</p><p>他的适应性很强，城市还是农村，或者郊区，泰迪狗都能很快适应环境。</p><p>泰迪狗适合所有家庭、单身人士或年老的主人。</p><p>性格和蔼可亲，能与猫等其他宠物和谐相处。</p><p>幼犬容意训练，他们喜欢学习技巧，热爱表演，参与娱乐活动。</p>',
      appearance:
        '<p>美丽的泰迪熊眼睛，圆圆的脸，还有毛茸茸的外套。</p><p>可爱是泰迪狗外表的代名词。</p><p>体型娇小，看起来很友好，没有攻击性，愿意交朋友。</p><p>泰迪狗是两种或多种不同犬种的混合品种，所以他们具有父母一些特征。</p><p>泰迪狗是宠物狗品种，继承了亲本品种的小体型。</p><p>虽然每只狗的体型可能略有不同，对于成年泰迪狗平均高度通常为 22 - 31 cm，体重为 2.72 - 6.5 kg。</p><p>全身覆盖着柔软蓬松的皮毛，圆圆的脸蛋，圆圆的眼睛闪闪发光。</p><p>娇小的鼻子，可爱的垂耳，还有一条蓬松的短尾巴卷在背上。</p><p>从外表上看，他们就像一只泰迪熊。</p><p>泰迪狗防过敏的毛皮柔软蓬松，有多种华丽的颜色，最常见的是棕色、白色、黑色、灰色和黄色。</p>',
      photos: [''],
      temperament:
        '<p>作为两种不同狗的混种，泰迪幼犬继承了父母所提供的优秀品质。</p><p>友善、深情、冷静。</p><p>与其他毛皮宝宝交朋友以及拥抱主人是他们最喜欢的活动之一。</p><p>喜欢玩捉迷藏游戏、解决谜题、追逐咀嚼玩具。</p><p>还喜欢自由漫步、游泳和抓取。</p><p>因为他们是注重家庭的狗，所以非常喜欢拥抱和宠爱。</p><p>对于孩子来说，泰迪狗是最好的毛茸朋友。</p><p>他们有耐心、温柔，可以和小孩子一起玩耍，活泼（或者调皮），可以让大一点的孩子开心。</p><p>训练泰迪狗也是一种有趣且有益的经历。</p><p>这些小狗喜欢学习课程来获得关注，热衷于给主人留下深刻的印象。</p><p>他们喜欢尝试新的技巧，自豪地炫耀他们所学到的东西。</p><p>当游戏时间结束时，泰迪狗会甜蜜、深情地等待拥抱。</p>',
      care: '<p>清洁护理： 泰迪熊的美容费用不高。</p><p>他们只需要每月洗澡一次，每周梳理一次，就可以保持皮毛干净、无缠结、有光泽。</p><p>建议检查和清洁他们的耳朵和眼睛，定期刷牙，根据需要修剪指甲。</p><p>运动关怀： 泰迪狗是一种顽皮、喜欢拥抱的小狗。</p><p>他们喜欢参加所有家庭活动，无论是户外运动游戏还是在家放松游戏。</p><p>泰迪狗喜欢在房子里闲逛，就像他们喜欢在空旷的场地上追球一样。</p><p>每天几次快走和一些室内活跃的玩耍时间就足以让泰迪熊保持快乐和健康。</p><p>健康： 泰迪狗是一种健康的品种，不像其他小型犬种那样容易出现许多健康问题。</p><p>有时，他们可能会出现牙齿问题、眼睛问题或耳朵感染等疾病。</p><p>建议保持泰迪狗的均衡饮食和优质狗粮，并提供适当的锻炼方案。</p><p>过度运动、过度喂养、粗暴玩耍和处理不当可能会导致严重的健康问题，应该避免。</p><p>寿命： 泰迪狗的寿命在12至18年之间。</p><p>泰迪狗在温暖有爱的环境，得到营养丰富的饮食和日常锻炼活动后，其预期寿命可以超过18岁。</p><p>训练： 泰迪狗是非常聪明的狗。</p><p>当他们得到适当的激励时，可很容易地接受培训。</p><p>为了让泰迪狗保持专注和渴望学习，最好保持训练课程简短且易于互动，使用积极的强化方法。</p><p>训练泰迪幼犬时，欢呼赞美和美味零食效果最佳。</p><p>一旦他们对所教的内容产生兴趣，他们就会变成听话、随和的学生。</p><p>泰迪幼犬的社交和牵引训练应该逐渐进行，最好每天几分钟。</p><p>尽管他们性格外向、善于交际、友善，但最好尽早让他们熟悉新的环境，应对各种事件。</p>',
      history:
        '<p>泰迪狗是在 2000 年前后的美国，特意将西施犬和卷毛比熊犬杂交而成的。</p><p>泰迪狗饲养员希望将这两个品种混合在一起，以便培育出体型与西施犬一样大小的可爱幼犬。</p><p>他们拥有了西施犬和比熊犬的适应性。</p><p>饲养员发现 Shichon（又名泰迪熊）越来越受欢迎，因为它们的皮毛过敏较低，对所有类型的家庭都很友好。</p><p>尽管泰迪狗的明确起源尚不清楚，但我们可以回顾一下西施犬、马耳他犬和卷毛比雄犬品种的历史，以更好地了解这个设计杂交品种。</p><p>西施犬是泰迪狗的亲本品种之一，据说是最古老的犬种之一，也是皇帝的最爱。</p><p>中国对西施犬品种的文化记录可以追溯到六世纪，它们是为了生活在宫殿中并取悦皇帝而饲养的。</p><p>马耳他犬是犬类贵族中的一员。</p><p>几个世纪以来，作为皇室和贵族的狗，马耳他狗一直在绘画、陶瓷和文学中出现。</p><p>马耳他幼犬是最有礼貌的小型宠物之一，它们听话、精力充沛，也很快乐、顽皮。</p><p>几个世纪以前，卷毛比雄犬在法国和西班牙非常受欢迎，出现在两国的皇室肖像中。</p><p>在 16 世纪，旅行的水手将卷毛比雄犬从特内里费岛（Tenerife）带到了欧洲。</p><p>比熊犬一出现，就以其深情甜美的天性和惹人喜爱的漂亮外表迅速俘获了宫女们的芳心，很快成为宫廷宠儿。</p><p>泰迪狗是送给世界各地爱狗人士的礼物。</p>',
    },
    properties: {
      type: '泰迪狗',
      energy: '中等',
      shedding: '低',
      training: '高',
      temperament: '热情、独立、聪明、爱心',
      weight: '2.72-6.5',
      height: '22-31',
      life: '12-18',
    },
  },
  husky: {
    details: {
      overview:
        '<p>西伯利亚雪橇犬是一种体型中等、耐力强的厚毛紧凑型雪橇犬，被驯养为组队在广阔的冰冻土地上以中等速度拉动轻负载雪橇的工作犬。</p><p>哈士奇友好、挑剔且有尊严。</p><p>哈士奇的杏仁形眼睛可以是棕色或蓝色，表现出敏锐但和蔼可亲甚至调皮的表情。</p><p>哈士奇脚步敏捷，以其看似轻松但有力量的步态闻名。</p><p>它们的体重不超过 30 千克，比它们魁梧的表亲阿拉斯加雪橇犬更小、更轻。</p><p>它们喜欢家庭生活，并与其他狗相处融洽。</p><p>哈士奇与生俱来的友好使他们成为无动于衷的看门狗。</p><p>它们精力充沛，无法抗拒地追逐小动物，因此安全的跑步空间是必须的。</p><p>哈士奇有一个独特的优点：天然干净，几乎没有狗的气味。</p>',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '哈士奇 / 西伯利亚雪橇犬',
      energy: '高',
      shedding: '高',
      training: '高',
      temperament: '温柔、顽皮、开朗',
      weight: '15.88-27.22',
      height: '50.8-58.42',
      life: '12-15',
    },
  },
  pomeranian: {
    details: {
      overview:
        '<p>小型博美犬长期以来一直受到皇室和平民的喜爱，被称为理想的伴侣。</p><p>华丽的皮毛、微笑、狡猾的脸和活泼的个性使波姆犬成为世界上最受欢迎的玩具品种之一。</p><p>博美犬结合了娇小的身体（不超过七磅）和威严的大狗风范。</p><p>丰富的双层被毛，其褶边延伸至胸部和肩膀，有近两打颜色以及各种图案和斑纹，但最常见的是橙色或红色。</p><p>博美犬警觉且聪明，很容易训练，对于有足够大的孩子知道玩具狗和玩具之间的区别的家庭来说，它们是优秀的看门狗和活泼的宠物。</p><p>博美犬很活跃，但可以通过室内玩耍和短距离散步来锻炼，所以他们在城市和郊区都很满意。</p><p>他们将轻松掌握技巧和游戏，尽管他们最喜欢的活动是为他们特殊的人带来欢笑和陪伴。</p>',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '博美',
      energy: '中等',
      shedding: '低',
      training: '高',
      temperament: '好奇、活泼、大胆',
      weight: '1.36-3.18',
      height: '17.78-22',
      life: '9-13',
    },
  },
  chihuahua: {
    details: {
      overview:
        '<p>吉娃娃是一只个性鲜明的小狗。</p><p>作为墨西哥的国家象征，这些警觉而有趣的“钱包狗”是美洲最古老的品种之一，其血统可以追溯到前哥伦布时代的古老王国。</p><p>吉娃娃是一只平衡、优雅的狗，举止像梗犬，体重不超过 6 磅。</p><p>圆形的“苹果”头是一个品种的标志。</p><p>直立的耳朵和饱满、明亮的眼睛极具表现力。</p><p>外套有多种颜色和图案，可长可短。</p><p>除了外套外，这些品种是相同的。</p><p>吉娃娃拥有忠诚、魅力和大狗的态度。</p><p>即使是小狗也需要训练，没有它，这个聪明的家伙会像小拿破仑一样统治你的家庭。</p><p>吉娃娃紧凑而自信，是理想的城市宠物。</p><p>它们太小了，不适合带孩子粗暴地生活，在寒冷的天气里必须特别小心，但吉娃娃是适应性强的，只要它们在自己喜欢的膝盖上得到很多美好的时光。</p>',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '吉娃娃',
      energy: '高等',
      shedding: '低',
      training: '高',
      temperament: '迷人、优雅、时髦',
      weight: '0.91-2.72',
      height: '12.7-30.48',
      life: '15-20',
    },
  },
  oldEnglishSheepdog: {
    details: {
      overview:
        '<p>古英国牧羊犬是典型的毛茸茸的狗，以其丰满的皮毛和巅峰的发型、独特的熊般的步态以及圆润、讨人喜欢的天性而闻名。</p><p>古英国牧羊犬是一只大而敏捷的狗，喜欢探索和嬉戏。</p><p>在古英国牧羊犬丰富的双层外套下，是一只肌肉发达、紧凑的牧羊犬，骨骼丰富，臀部很大，肩高 21 或 22 英寸。</p><p>他们的眼睛（如果你能看到他们时）是深棕色或蓝色，或者两者各有一。</p><p>古英国牧羊犬品种标准称，头骨“宽敞且相当方正，为脑力提供了充足的空间”。</p><p>古英国牧羊犬以熊一样的姿态移动，但以其敏捷而闻名。</p><p>这些强壮、身体健全的工人需要定期锻炼。</p><p>同样著名的是他们的许多优良家犬品质：警惕、勇气、善良和智慧。</p><p>古英国牧羊犬非常适合儿童，是耐心、保护性的玩伴。</p><p>它们是明智的看门狗，以响亮的吠叫而闻名。</p>',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '古代英国牧羊犬',
      energy: '中等',
      shedding: '较高',
      training: '高',
      temperament: '聪明、温和、适应性强',
      weight: '27.22-38.56',
      height: '50.8-60.96',
      life: '10-12',
    },
  },
  samoyed: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  chowChow: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  goldenRetriever: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  bichonFrise: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  englishBulldog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  alaskanMalamute: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  tibetanMastiff: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  labradorRetriever: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  yorkshireTerrier: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  borderCollie: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  pug: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  greatPyrenees: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  schnauzer: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  japaneseSpitz: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  germanShepherd: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  scottishCollie: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  rottweiler: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  shetlandSheepdog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  westHighlandWhiteTerrier: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  corgi: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  cockerSpaniel: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  doberman: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  caucasianMountain: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  saintBernard: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  dachshund: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  pekingese: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  maltese: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  sharPei: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  bullTerrier: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  papillon: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  beagle: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  berneseMountainDog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  dalmatian: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  poodle: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  akita: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  teacupDog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  pitbull: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  belgianMalinois: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  shibaInu: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  wolfdog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  greyhound: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  kunmingWolfdog: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  greatDane: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  caneCorso: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  afghanHound: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  belgianShepherd: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
  dogoArgentino: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
};

export const CATS_MAP: IPetMap = {
  ragdoll: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '布偶猫',
      energy: '低',
      shedding: '中',
      training: '中',
      temperament: '友好、随和、可爱、善于交际',
      weight: '4.5-9',
      height: '101.6',
      life: '12-17',
    },
  },
  siamese: {
    details: {
      overview: '',
      characteristics: '',
      appearance: '',
      photos: [''],
      temperament: '',
      care: '',
      history: '',
    },
    properties: {
      type: '',
      energy: '',
      shedding: '',
      training: '',
      temperament: '',
      weight: '',
      height: '',
      life: '',
    },
  },
};
