DROP TABLE IF EXISTS public.image;

CREATE TABLE IF NOT EXISTS public.image (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   hash VARCHAR(255) NOT NULL,
   category VARCHAR(255),
   created_time TIMESTAMP NOT NULL DEFAULT NOW(),
   update_time TIMESTAMP NOT NULL DEFAULT NOW()
);
