import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  '2207': [{
    'date': '2022-01-28 16:49',
    'sourceUrl': 'https://www.bilibili.com/video/BV19q4y187WH',
    'referer': null,
    'imageUrl': 'BV19q4y187WH',
    'tagIds': ['food'],
    'publisher': '钳子拯救没胃口',
    'description': '12月拍摄的，用了将近一个月的时间剪辑，好不容易在年前剪辑出来了，正当时，提前两天 祝大家新年快乐，年年有余',
    'typeId': '2207',
    'id': '9',
    'detail': '',
    'title': '体验查干湖冬捕，出鱼的那一刻，不自觉飙出了脏话',
    'views': 318407
  }],
  '110105': [{
    'date': '2019-12-10 19:08',
    'sourceUrl': 'https://www.bilibili.com/video/BV1eJ411y7nF',
    'referer': null,
    'imageUrl': 'BV1eJ411y7nF',
    'tagIds': ['food'],
    'publisher': '盗月社食遇记',
    'description': '4种烤鸭卷饼大法，感觉自己很优雅的时候......翻车了。',
    'typeId': '110105',
    'id': '1',
    'detail': '',
    'title': '最便宜的北京烤鸭？滋滋冒油，师傅现场片着吃！',
    'views': 1997117
  }],
  '4212': [{
    'date': '2021-10-26 10:14',
    'sourceUrl': 'https://www.bilibili.com/video/BV1FU4y1c7hF',
    'referer': null,
    'imageUrl': 'BV1FU4y1c7hF',
    'tagIds': ['flower'],
    'publisher': '西部决策D视频',
    'description': '10月25日，湖北咸宁，拥有“中国桂花之乡”美誉的咸宁境内桂花大面积盛开，迎来最佳观赏期。大街小巷、景区公园里的桂花竞相绽放，盈满枝头。受天气影响，今年咸宁桂花大面积盛开的时间推迟了20天左右，许多市民趁着晴好天气走出户外赏桂闻香，欣赏最美秋色。',
    'typeId': '4212',
    'id': '4',
    'detail': '',
    'title': '中国桂花之乡迎来最佳观赏期，市民：整个城市都是金黄色香气扑鼻',
    'views': 846
  }, {
    'date': '2021-06-08 23:15',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Vf4y187YJ',
    'referer': null,
    'imageUrl': 'BV1Vf4y187YJ',
    'tagIds': ['tea'],
    'publisher': '贝贝的茶生活',
    'description': '青砖茶\n一砖有六斤重\n第一次见这么撬茶的\n开眼界了\n最早蒙古人喜欢用它熬奶茶\n陈化久了的青砖\n清饮起来\n口感甜润\n茶气足',
    'typeId': '4212',
    'id': '5',
    'detail': '',
    'title': '老黑茶 青砖茶 老黑茶 赵李桥茶厂',
    'views': 4564
  }],
  '4201': [{
    'date': '2023-06-30 09:38',
    'sourceUrl': 'https://www.bilibili.com/video/BV1fF411d7VR',
    'referer': null,
    'imageUrl': 'BV1fF411d7VR',
    'tagIds': ['food'],
    'publisher': '闻哥美食记',
    'description': '-',
    'typeId': '4201',
    'id': '3',
    'detail': '',
    'title': '武汉传统三鲜豆皮制作方法',
    'views': 2721
  }, {
    'date': '2021-04-18 19:59',
    'sourceUrl': 'https://www.bilibili.com/video/BV1G84y1F7ha',
    'referer': null,
    'imageUrl': 'BV1G84y1F7ha',
    'tagIds': ['food'],
    'publisher': '肉肉大搜索',
    'description': '武汉“最便宜的大饼豆皮”，6元一份，大哥甩锅20多年从未失手，锅在甩、饼在飞',
    'typeId': '4201',
    'id': '2',
    'detail': '',
    'title': '武汉“最便宜的大饼豆皮”，6元一份，大哥甩锅20多年从未失手，锅在甩、饼在飞',
    'views': 1840877
  }],
  '4401': [{
    'date': '2023-06-29 16:56',
    'sourceUrl': 'https://www.bilibili.com/video/BV1jM4y1772m',
    'referer': null,
    'imageUrl': 'BV1jM4y1772m',
    'tagIds': ['fruit'],
    'publisher': '品城记本地版',
    'description': '今年是荔枝的丰收大年，从几个月前开始，我们便开始奔走各地，品尝了不同品种的荔枝。而众所周知，“晚熟荔枝”是荔枝中的极品，无论口感还是甜度，都远比早熟荔枝要好。而提到哪里的晚熟荔枝最出名，那一定就是广州增城，要说增城荔枝哪个品种最为著名，那一定就是它——仙进奉。仙进奉是增城仙村独有的一款荔枝，其产量极其稀少，在市面上极为罕见，其果肉爽脆无渣、肉厚核小，而且拥有极高的甜度，不少吃过它的人都表示：幸亏仙进奉比较晚才上市，不然其他荔枝都索然无味了！',
    'typeId': '4401',
    'id': '6',
    'detail': '',
    'title': '【品城记】终于等到我们心中的荔枝之神——增城仙进奉！肉厚核小甜度极高！吃过仙进奉，其它荔枝都索然无味了！',
    'views': 80108
  }, {
    'date': '2020-03-09 18:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV1sE411s7SE',
    'referer': null,
    'imageUrl': 'BV1sE411s7SE',
    'tagIds': ['fruit'],
    'publisher': '广东印记',
    'description': '《广东印记》第二季——第7集\n增城挂绿是荔枝中的珍稀品种，是增城市著名的特产，现存活在增城荔城镇挂绿园的那株挂绿树是挂绿荔枝品种的老祖宗，已由它成功培育了好几代的挂绿子孙树种。本集介绍增城挂绿的得名来源和挂绿品种成为荔枝珍品深深影响当地人的过程。增城挂绿因果实表面有一道绿线环绕而得名，但因产量稀少而价值奇高。而如今，在增城，挂绿已经成为了一个独特的文化符号，饱含了增城人浓浓的挂绿情。',
    'typeId': '4401',
    'id': '7',
    'detail': '',
    'title': '【广东美食】能拍出55万元RMB天价一颗的广东增城挂绿荔枝到底贵在哪？跟我一起来认识一下吧！广东印记——增城挂绿荔枝',
    'views': 78040
  }],
  '4403': [{
    'date': '2023-06-22 11:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Dc411M78h',
    'referer': null,
    'imageUrl': 'BV1Dc411M78h',
    'tagIds': ['food'],
    'publisher': '华仔好好吃',
    'description': '',
    'typeId': '4403',
    'id': '8',
    'detail': '',
    'title': '深圳光明最好吃的乳鸽？竟隐藏在藏在小巷里，本地人才知道',
    'views': 16569
  }]
};
