import { IClanMap, IWarhammerClassifier } from '@w-monorepo/warhammer';

export const WEAPON_CLASSIFIERS: IWarhammerClassifier[] = [
  {
    nameCN: '武器',
    files: [],
    id: 'weapon',
    directory: 'weapon',
    order: 1,
  },
];

export const WEAPON_CLASSIFIERS_MAP: IClanMap = {
  Great_Sword: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Great_Sword.png',
      path: 'assets/images/weapons/Great_Sword.png',
      name: 'Great Sword',
      nameCN: '大剑 / 巨剑',
      description: '纵斩、横斩、蓄力斩等',
      id: 'Great_Sword',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Long_Sword: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Long_Sword.png',
      path: 'assets/images/weapons/Long_Sword.png',
      name: 'Long Sword',
      nameCN: '太刀 / 铁剑 / 长片手剑 / 牙签 / 膝盖收割者',
      description: '拔刀斩、纵斩、戳刺、上挑、袈裟斩、气刃斩',
      id: 'Long_Sword',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Sword_and_Shield: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Sword_and_Shield.png',
      path: 'assets/images/weapons/Sword_and_Shield.png',
      name: 'Sword and Shield',
      nameCN: '片手剑 / 单手剑',
      description: '连续斩击、盾击、翻滚前击、跳斩',
      id: 'Sword_and_Shield',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Dual_Blades: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Dual_Blades.png',
      path: 'assets/images/weapons/Dual_Blades.png',
      name: 'Dual Blades / Double Sword',
      nameCN: '双剑 / 双刀',
      description: '‌二连斩、挥斩、鬼人化',
      id: 'Dual_Blades',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Hammer: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Hammer.png',
      path: 'assets/images/weapons/Hammer.png',
      name: 'Hammer',
      nameCN: '大锤 / 铁锤',
      description: '三连击‌，蓄力击',
      id: 'Hammer',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Hunting_Horn: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Hunting_Horn.png',
      path: 'assets/images/weapons/Hunting_Horn.png',
      name: 'Hunting Horn',
      nameCN: '片手剑 / 单手剑',
      description: '钝击，“演奏”',
      id: 'Hunting_Horn',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Lance: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Lance.png',
      path: 'assets/images/weapons/Lance.png',
      name: 'Lance',
      nameCN: '长枪',
      description: '中段刺、上段刺、突进',
      id: 'Lance',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Gunlance: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Gunlance.png',
      path: 'assets/images/weapons/Gunlance.png',
      name: 'Gunlance',
      nameCN: '铳枪',
      description: '突刺、炮击',
      id: 'Gunlance',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Switch_Axe: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Switch_Axe.png',
      path: 'assets/images/weapons/Switch_Axe.png',
      name: 'Switch Axe',
      nameCN: '斩击斧 / 剑斧 / 指甲刀',
      description:
        '‌斧：横斩、上捞斩、直斩、突进斩、变形斩，剑：直砍、二连斩、‌变形斩',
      id: 'Switch_Axe',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Charge_Blade: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Charge_Blade.png',
      path: 'assets/images/weapons/Charge_Blade.png',
      name: 'Charge Blade',
      nameCN: '盾斧 / 充能斧 / 蓄力斧',
      description: '斩击、盾击',
      id: 'Charge_Blade',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Insect_Glaive: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Insect_Glaive.png',
      path: 'assets/images/weapons/Insect_Glaive.png',
      name: 'Insect Glaive',
      nameCN: '操虫棍 / 虫棍 / 长刀',
      description: '连续斩击、盾击、翻滚前击、跳斩',
      id: 'Insect_Glaive',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Light_Bowgun: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Light_Bowgun.png',
      path: 'assets/images/weapons/Light_Bowgun.png',
      name: 'Light Bowgun',
      nameCN: '轻弩 / 轻弩炮',
      description: '瞄准、射击、连续射击',
      id: 'Light_Bowgun',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Heavy_Bowgun: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Heavy_Bowgun.png',
      path: 'assets/images/weapons/Heavy_Bowgun.png',
      name: 'Heavy Bowgun',
      nameCN: '重弩 / 重弩炮',
      description: '蹲射',
      id: 'Heavy_Bowgun',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
  Bow: {
    parentId: 'weapon',
    file: {
      heroNickName: '',
      heroAvatarPath: 'assets/images/weapons/Bow.png',
      path: 'assets/images/weapons/Bow.png',
      name: 'Bow',
      nameCN: '弓箭 / 弓',
      description: '普通射击、蓄力射击、特殊射击',
      id: 'Bow',
      contributors: [],
      heroName: '',
      order: 1,
    },
  },
};
