import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GalleryComponent, IItemCard } from '@w-monorepo/ui';
import { PetGalleryComponent } from '../../components/pet-gallery/pet-gallery.component';

@Component({
  selector: 'pet-on-sale',
  standalone: true,
  imports: [CommonModule, GalleryComponent, PetGalleryComponent],
  templateUrl: './on-sale.component.html',
  styleUrl: './on-sale.component.scss',
})
export class OnSaleComponent {
  protected pets: IItemCard[] = [
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog1.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog2.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog3.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog4.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog5.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog6.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog7.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog8.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog9.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog10.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog11.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog12.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog13.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog14.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
    {
      date: '',
      description: '伯恩山犬',
      detail: '',
      id: '',
      imageUrl: 'assets/images/dogs/dog15.jpg',
      tagIds: [],
      title: '小乖',
      typeId: '',
      price: {
        discountPercent: 100,
        initial: '2000',
        final: '2000',
      },
    },
  ];
}
