import { ITag } from '@w-monorepo/ui';
import { IArticleMap } from '@w-monorepo/interfaces';

export const PS5_TAGS: ITag[] = [{ id: 'all', name: '不限' }];

export const PS4_TAGS: ITag[] = [{ id: 'all', name: '不限' }];

export const CARTRIDGE_MAP: IArticleMap = {
  ps5: [
    {
      sourceUrl: '/wiki/sqF1NA',
      date: '',
      description: '怪物猎人·荒野，一场惊心动魄的狩猎即将来临。',
      detail:
        'https://www.openshop.com.hk/_c_product_36108.html?srsltid=AfmBOoqEi9ROCSFVs_JtYeftm2ZHTDqhugDqKY6GnUghUHf8Atbft4B_',
      id: 'sqF1NA',
      imageUrl: 'assets/images/ps5/F_sqF1NA.png',
      tagIds: ['新品', '怪物猎人'],
      title: 'Monster Hunter Wilds',
      price: {
        discountPercent: 100,
        initial: '498.00',
        final: '498.00',
      },
    },
    {
      sourceUrl: '/wiki/1qug5y',
      date: '',
      description:
        '如临真实战场，畅享爽快的一骑当千动作！无名英雄闯荡三国乱世的“真・三国无双”系列新作。',
      detail: '',
      id: '1qug5y',
      imageUrl: 'assets/images/ps5/F_1qug5y.png',
      tagIds: ['新品', '三国'],
      title: '真三国无双·起源',
      price: {
        discountPercent: 100,
        initial: '485.00',
        final: '485.00',
      },
    },
    {
      sourceUrl: '/wiki/zjaAsj',
      date: '',
      description: '奎爷这次要斩杀多少神',
      detail: '',
      id: 'zjaAsj',
      imageUrl: 'assets/images/ps5/F_zjaAsj.jpg',
      tagIds: ['动作', '冒险'],
      title: '战神 诸神黄昏',
      price: {
        discountPercent: 100,
        initial: '258.00',
        final: '258.00',
      },
    },
    {
      sourceUrl: '/wiki/RitaOO',
      date: '',
      description: '能吃就行！',
      detail: '',
      id: 'RitaOO',
      imageUrl: 'assets/images/ps5/F_RitaOO.jpg',
      tagIds: ['多人合作', '休闲'],
      title: '胡闹厨房 全都好吃',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '搬家？还是一起胡闹一番？',
      detail: '',
      id: 'Vw2M5v',
      imageUrl: 'assets/images/ps5/F_Vw2M5v.jpg',
      tagIds: ['多人合作', '休闲'],
      title: '胡闹搬家2',
      price: {
        discountPercent: 100,
        initial: '148.00',
        final: '148.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '那个游戏5',
      detail: '',
      id: 'F_0pcTPp',
      imageUrl: 'assets/images/ps5/F_0pcTPp.jpg',
      tagIds: ['犯罪', '沙盒'],
      title: 'GTA5',
      price: {
        discountPercent: 100,
        initial: '168.00',
        final: '168.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100614033',
      date: '',
      description:
        '通过强化的图形效果、Roguelike生存体验“赴死之旅”等游戏模式以及更多其他内容，探索艾莉和埃比的故事。',
      detail: '',
      id: 'nkC04A',
      imageUrl: 'assets/images/ps5/F_nkC04A.png',
      tagIds: ['剧情', '末日'],
      title: '最后生还者·PART2',
      price: {
        discountPercent: 100,
        initial: '268.00',
        final: '268.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=413895178',
      date: '',
      description:
        '带领乔尔和艾莉穿越末日后的美国，遇见令人难忘的盟友和敌人，踏上一段充满挑战的旅程。',
      detail: '',
      id: 'CsDawL',
      imageUrl: 'assets/images/ps5/F_CsDawL.png',
      tagIds: ['剧情', '末日'],
      title: '最后生还者·PART1',
      price: {
        discountPercent: 100,
        initial: '325.00',
        final: '325.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100994533',
      date: '',
      description: '传说的起点…',
      detail: '',
      id: 'yjrdzh',
      imageUrl: 'assets/images/ps5/F_yjrdzh.png',
      tagIds: ['经典', '重制版', '勇者斗恶龙'],
      title: '勇者斗恶龙III',
      price: {
        discountPercent: 100,
        initial: '280.00',
        final: '280.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100994628',
      date: '',
      description: '玩家将化身历代皇帝，与七英雄展开长达数千年的战斗。',
      detail: '',
      id: 'rTujpY',
      imageUrl: 'assets/images/ps5/F_rTujpY.png',
      tagIds: ['经典', '重制版'],
      title: '浪漫沙加2 七英雄的复仇',
      price: {
        discountPercent: 100,
        initial: '448.00',
        final: '448.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100500303',
      date: '',
      description:
        '克劳德一行人脱离魔晄都市米德加，跨越命运之墙，迈入未知的荒野旅程。',
      detail: '',
      id: 'IP44Jn',
      imageUrl: 'assets/images/ps5/F_IP44Jn.png',
      tagIds: ['经典', '重制版'],
      title: '最终幻想7 重生',
      price: {
        discountPercent: 100,
        initial: '375.00',
        final: '375.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100500338',
      date: '',
      description:
        '从“人生低谷”东山再起的男人——春日一番，以及面临“人生最后”之战的男人——桐生一马',
      detail: '',
      id: 'PLu8nA',
      imageUrl: 'assets/images/ps5/F_PLu8nA.png',
      tagIds: ['如龙'],
      title: '人中之龙8',
      price: {
        discountPercent: 100,
        initial: '238.00',
        final: '238.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=101242113',
      date: '',
      description:
        '在遥远的未来，巨型机器在地球各处游荡，幸运的少数人类结成独特的聚落求生，并在杂草丛生的失落文明废墟中扎下根来。',
      detail: '',
      id: 'Q1Z0cM',
      imageUrl: 'assets/images/ps5/F_Q1Z0cM.png',
      tagIds: ['机甲', '冒险', '开放世界', '重制版'],
      title: '《地平线 零之曙光™》',
      price: {
        discountPercent: 100,
        initial: '289.00',
        final: '289.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100815863',
      date: '',
      description:
        '片段破碎，却又多彩的故事──以“交界地”为舞台登场的角色们各有主张，于是在利害关系之下谱成的群像剧，就此展开。',
      detail: '',
      id: 'xc7moB',
      imageUrl: 'assets/images/ps5/F_xc7moB.png',
      tagIds: ['魂'],
      title: '艾尔登法环',
      price: {
        discountPercent: 100,
        initial: '238.00',
        final: '238.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description:
        '人类的命运岌岌可危。地球为怪异而强大的生物所肆虐，惨遭遗弃。',
      detail: '',
      id: 'GhIrMN',
      imageUrl: 'assets/images/ps5/F_GhIrMN.jpg',
      tagIds: ['动作', '冒险'],
      title: '剑星',
      price: {
        discountPercent: 100,
        initial: '388.00',
        final: '388.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '霍格沃兹的魔法世界',
      detail: '',
      id: 'hwmQMD',
      imageUrl: 'assets/images/ps5/F_hwmQMD.jpg',
      tagIds: ['开放世界', '魔法'],
      title: '霍格沃兹之遗',
      price: {
        discountPercent: 100,
        initial: '228.00',
        final: '228.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '强与更强',
      detail: '',
      id: 'QvkUHP',
      imageUrl: 'assets/images/ps5/F_QvkUHP.jpg',
      tagIds: ['格斗', '动作'],
      title: '街霸6',
      price: {
        discountPercent: 100,
        initial: '238.00',
        final: '238.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '2K系列 25新作',
      detail: '',
      id: '7xZ884',
      imageUrl: 'assets/images/ps5/F_7xZ884.jpg',
      tagIds: ['体育'],
      title: 'NBA 2K25',
      price: {
        discountPercent: 100,
        initial: '258.00',
        final: '258.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '2K系列 25新作 全明星版本',
      detail: '',
      id: 'olHS5N',
      imageUrl: 'assets/images/ps5/F_olHS5N.jpg',
      tagIds: ['体育'],
      title: 'NBA 2K25 全明星版本',
      price: {
        discountPercent: 100,
        initial: '398.00',
        final: '398.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100638045',
      date: '',
      description:
        '在幕府统治了三个世纪之后，西方的黑船袭击了日本的边界，这个国家陷入了动荡不安的状态。',
      detail: '',
      id: 'aM0Xd9',
      imageUrl: 'assets/images/ps5/F_aM0Xd9.png',
      tagIds: ['动作'],
      title: '浪人崛起',
      price: {
        discountPercent: 100,
        initial: '290.00',
        final: '290.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '与旅伴追随者一起，让我们踏入一场独一无二的冒险吧。',
      detail: '',
      id: 'FlWna3',
      imageUrl: 'assets/images/ps5/F_FlWna3.jpg',
      tagIds: ['角色扮演', '动作'],
      title: '龙之信条2',
      price: {
        discountPercent: 100,
        initial: '348.00',
        final: '348.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '错综复杂的人际关系将使得游戏更具有互动性。',
      detail: '',
      id: 'iCUaf7',
      imageUrl: 'assets/images/ps5/F_iCUaf7.jpg',
      tagIds: ['策略', '战棋', '三国', '重制版'],
      title: '三国之8 重制版',
      price: {
        discountPercent: 100,
        initial: '398.00',
        final: '398.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description:
        '探索有史以来最大的漫威宇宙纽约市，包括布鲁克林与皇后区这两个新的行政区，以及科尼岛等更多地点。',
      detail: '',
      id: 'gTYtNt',
      imageUrl: 'assets/images/ps5/F_gTYtNt.jpg',
      tagIds: ['动作', '开放世界'],
      title: '漫威蜘蛛侠2',
      price: {
        discountPercent: 100,
        initial: '318.00',
        final: '318.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '复仇者联盟、X战警和神奇四侠,还有另一个黑暗宇宙等待探索。',
      detail: '',
      id: 'wiCeYA',
      imageUrl: 'assets/images/ps5/F_wiCeYA.jpg',
      tagIds: ['卡牌', '回合制', '战术策略'],
      title: '漫威 午夜之子',
      price: {
        discountPercent: 100,
        initial: '148.00',
        final: '148.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100979260',
      date: '',
      description: '和Astro一起来一场超大型太空冒险吧！',
      detail: '',
      id: 'et69sO',
      imageUrl: 'assets/images/ps5/F_et69sO.png',
      tagIds: ['宇宙'],
      title: '宇宙机器人',
      price: {
        discountPercent: 100,
        initial: '360.00',
        final: '360.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100742499',
      date: '',
      description: '鸟山明·沙漠大冒险！',
      detail: '',
      id: 'LLD6Lp',
      imageUrl: 'assets/images/ps5/F_LLD6Lp.png',
      tagIds: ['机甲'],
      title: 'Sand Land',
      price: {
        discountPercent: 100,
        initial: '428.00',
        final: '428.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '',
      detail: '',
      id: 'V7nRXQ',
      imageUrl: 'assets/images/ps5/F_V7nRXQ.jpg',
      tagIds: ['格斗'],
      title: '龙珠 超宇宙2',
      price: {
        discountPercent: 100,
        initial: '168.00',
        final: '168.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100549095',
      date: '',
      description:
        '召集你的团队，回到被遗忘的国度，开启一段记载着友谊与背叛、牺牲与生存、以及至上力量诱惑的传奇故事。',
      detail: '',
      id: 'DOeaue',
      imageUrl: 'assets/images/ps5/F_DOeaue.png',
      tagIds: ['角色扮演', '剧情'],
      title: '博德之门3',
      price: {
        discountPercent: 100,
        initial: '325.00',
        final: '325.00（无中文） ',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100967065',
      date: '',
      description:
        '收到已过世的妻子玛丽寄来的信，詹姆斯借机来到充满回忆的城镇「寂静岭」。',
      detail: '',
      id: '5JG0ch',
      imageUrl: 'assets/images/ps5/F_5JG0ch.png',
      tagIds: ['恐怖', '剧情'],
      title: '寂静岭2',
      price: {
        discountPercent: 100,
        initial: '340.00',
        final: '340.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=100979262',
      date: '',
      description:
        '由于神秘怪物“时间吞噬者”造成的时空扭曲，索尼克和夏特开始了各自的故事。',
      detail: '',
      id: '79f2Os',
      imageUrl: 'assets/images/ps5/F_79f2Os.png',
      tagIds: ['动作'],
      title: '索尼克×夏特 世代重启',
      price: {
        discountPercent: 100,
        initial: '298.00',
        final: '298.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=101078257',
      date: '',
      description: '《EA SPORTS FC™ 25》将为您带来更多为俱乐部奋勇争胜的方式。',
      detail: '',
      id: 'mELJig',
      imageUrl: 'assets/images/ps5/F_mELJig.png',
      tagIds: ['足球', '体育'],
      title: '《EA SPORTS FC™ 25》',
      price: {
        discountPercent: 100,
        initial: '298.00',
        final: '298.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description:
        '欢迎来到2042年，世界正处于战争的边缘，一种不属于任何国家的新型士兵“无邦者”从人类历史上最大的危机中应运而生。',
      detail: '',
      id: 'gFD4WY',
      imageUrl: 'assets/images/ps5/F_gFD4WY.jpg',
      tagIds: ['射击'],
      title: '战地风云2042',
      price: {
        discountPercent: 100,
        initial: '138.00',
        final: '138.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '猫的冒险',
      detail: '',
      id: 'i0Q4jf',
      imageUrl: 'assets/images/ps5/F_i0Q4jf.jpg',
      tagIds: ['冒险'],
      title: '流浪 Stray',
      price: {
        discountPercent: 100,
        initial: '168.00',
        final: '168.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '通往遥远天空的轨迹是否会成为赛姆利亚大陆的未来————',
      detail: '',
      id: 'ZDtrNU',
      imageUrl: 'assets/images/ps5/F_ZDtrNU.jpg',
      tagIds: ['剧情'],
      title: '界之轨迹',
      price: {
        discountPercent: 100,
        initial: '468.00',
        final: '468.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '斩鬼队，出征！',
      detail: '',
      id: 'vA7Ghw',
      imageUrl: 'assets/images/ps5/F_vA7Ghw.jpg',
      tagIds: ['同人'],
      title: '鬼灭之刃 火之神血风谭',
      price: {
        discountPercent: 100,
        initial: '198.00',
        final: '198.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '黄昏 阿尼亚 约尔',
      detail: '',
      id: 'aVVYYe',
      imageUrl: 'assets/images/ps5/F_aVVYYe.jpg',
      tagIds: ['同人'],
      title: '间谍×过家家：日记大作战',
      price: {
        discountPercent: 100,
        initial: '288.00',
        final: '288.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '装甲射击',
      detail: '',
      id: '5GqnkL',
      imageUrl: 'assets/images/ps5/F_5GqnkL.jpg',
      tagIds: ['双人对战'],
      title: '天翔铁骑',
      price: {
        discountPercent: 100,
        initial: '248.00',
        final: '248.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '开着卡车行驶在美国公路上',
      detail: '',
      id: 'BaSHLJ',
      imageUrl: 'assets/images/ps5/F_BaSHLJ.jpg',
      tagIds: ['模拟'],
      title: '卡车司机 美国梦',
      price: {
        discountPercent: 100,
        initial: '268.00',
        final: '268.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '跟着节拍敲鼓',
      detail: '',
      id: 'e5SA14',
      imageUrl: 'assets/images/ps5/F_e5SA14.jpg',
      tagIds: ['音游'],
      title: '太鼓之达人：咚咚雷音祭',
      price: {
        discountPercent: 100,
        initial: '358.00',
        final: '358.00',
      },
    },
    {
      sourceUrl: 'https://www.sofmap.com/product_detail.aspx?sku=101304042',
      date: '',
      description: '维纳斯璀璨假期。在这座岛，怦然心动的每一刻。',
      detail: '',
      id: 'lYCcDd',
      imageUrl: 'assets/images/ps5/F_lYCcDd.png',
      tagIds: ['恋爱', '即将推出'],
      title: '死或生 Xtreme',
      price: {
        discountPercent: 100,
        initial: '--.--',
        final: '--.--',
      },
    },
  ],
  ps4: [
    {
      sourceUrl: '',
      date: '',
      description: '侠盗猎车手 4',
      detail: '',
      id: 'oPkHeT',
      imageUrl: 'assets/images/ps4/oPkHeT.jpg',
      tagIds: ['开放世界'],
      title: 'GTA4',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '侠盗猎车手 5',
      detail: '',
      id: 'XYC0X0',
      imageUrl: 'assets/images/ps4/XYC0X0.jpg',
      tagIds: ['开放世界'],
      title: 'GTA5',
      price: {
        discountPercent: 100,
        initial: '168.00',
        final: '168.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: 'NBA',
      detail: '',
      id: '7czZCI',
      imageUrl: 'assets/images/ps4/7czZCI.jpg',
      tagIds: ['体育'],
      title: 'NBA 2K25',
      price: {
        discountPercent: 100,
        initial: '198.00',
        final: '198.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '如龙3',
      detail: '',
      id: 'Yx0xXo',
      imageUrl: 'assets/images/ps4/Yx0xXo.jpg',
      tagIds: ['剧情'],
      title: '人中之龙3 如龙3',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '如龙4',
      detail: '',
      id: 'tZAlwn',
      imageUrl: 'assets/images/ps4/tZAlwn.jpg',
      tagIds: ['剧情'],
      title: '人中之龙4 如龙4',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '如龙5',
      detail: '',
      id: 'bmlR63',
      imageUrl: 'assets/images/ps4/bmlR63.jpg',
      tagIds: ['剧情'],
      title: '人中之龙5 如龙5',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '梦幻旅行',
      detail: '',
      id: 'rBVwd0',
      imageUrl: 'assets/images/ps4/rBVwd0.jpg',
      tagIds: ['双人', '冒险'],
      title: '双人成行',
      price: {
        discountPercent: 100,
        initial: '168.00',
        final: '168.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '侦探',
      detail: '',
      id: 'VxBWxJ',
      imageUrl: 'assets/images/ps4/VxBWxJ.jpg',
      tagIds: ['剧情'],
      title: '审判之眼：死神的遗言',
      price: {
        discountPercent: 100,
        initial: '188.00',
        final: '188.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '侦探',
      detail: '',
      id: 'RcdJsA',
      imageUrl: 'assets/images/ps4/RcdJsA.jpg',
      tagIds: ['剧情'],
      title: '审判之逝：湮灭的记忆',
      price: {
        discountPercent: 100,
        initial: '288.00',
        final: '288.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '怪物猎人，你准备好狩猎了吗？',
      detail: '',
      id: '1v8dFO',
      imageUrl: 'assets/images/ps4/1v8dFO.jpg',
      tagIds: ['狩猎', '动作'],
      title: '怪物猎人：世界·冰原DLC',
      price: {
        discountPercent: 100,
        initial: '238.00',
        final: '238.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '龙 vs 八神',
      detail: '',
      id: '8cIPQF',
      imageUrl: 'assets/images/ps4/8cIPQF.jpg',
      tagIds: ['格斗'],
      title: '拳皇对街霸',
      price: {
        discountPercent: 100,
        initial: '178.00',
        final: '178.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '生化危机2',
      detail: '',
      id: '1rNhv9',
      imageUrl: 'assets/images/ps4/1rNhv9.jpg',
      tagIds: ['剧情', '恐怖', '重制版'],
      title: '生化危机2 重制版',
      price: {
        discountPercent: 100,
        initial: '188.00',
        final: '188.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '生化危机3',
      detail: '',
      id: 'fgdblL',
      imageUrl: 'assets/images/ps4/fgdblL.jpg',
      tagIds: ['剧情', '恐怖', '重制版'],
      title: '生化危机3 重制版',
      price: {
        discountPercent: 100,
        initial: '188.00',
        final: '188.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '过着平凡高中生活的主人公，由于某种契机而闯入异世界“达识”。',
      detail: '',
      id: 'RNq2gI',
      imageUrl: 'assets/images/ps4/RNq2gI.jpg',
      tagIds: ['角色扮演'],
      title: '真·女神转生5',
      price: {
        discountPercent: 100,
        initial: '298.00',
        final: '298.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '能吃就行！',
      detail: '',
      id: 'IU5FHQ',
      imageUrl: 'assets/images/ps4/IU5FHQ.jpg',
      tagIds: ['多人合作', '休闲'],
      title: '胡闹厨房 全都好吃',
      price: {
        discountPercent: 100,
        initial: '148.00',
        final: '148.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '搬家？还是一起胡闹一番？',
      detail: '',
      id: 'aZYBvj',
      imageUrl: 'assets/images/ps4/aZYBvj.jpg',
      tagIds: ['多人合作', '休闲'],
      title: '胡闹搬家',
      price: {
        discountPercent: 100,
        initial: '148.00',
        final: '148.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '验纵横驰骋的美国边境生活',
      detail: '',
      id: '71L2hk',
      imageUrl: 'assets/images/ps4/71L2hk.jpg',
      tagIds: ['角色扮演', '动作', '开放世界'],
      title: '荒野大镖客1',
      price: {
        discountPercent: 100,
        initial: '238.00',
        final: '238.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '验纵横驰骋的美国边境生活',
      detail: '',
      id: 'tegzNy',
      imageUrl: 'assets/images/ps4/tegzNy.jpg',
      tagIds: ['角色扮演', '动作', '开放世界'],
      title: '荒野大镖客2',
      price: {
        discountPercent: 100,
        initial: '158.00',
        final: '158.00',
      },
    },
    {
      sourceUrl: '',
      date: '',
      description: '但丁和尼禄两大主角回归，还加入了神秘的新角色“V”',
      detail: '',
      id: '6yu2Px',
      imageUrl: 'assets/images/ps4/6yu2Px.jpg',
      tagIds: ['动作'],
      title: '鬼泣5',
      price: {
        discountPercent: 100,
        initial: '148.00',
        final: '148.00',
      },
    },
  ],
  switch: [
    {
      sourceUrl: '/wiki/cZTCm5',
      date: '',
      description: '塞尔达传说，梦在延续！',
      detail: '',
      id: 'cZTCm5',
      imageUrl: 'assets/images/switch/F_cZTCm5.png',
      tagIds: ['角色扮演', '开放世界'],
      title: '塞尔达传说·王国之泪',
      price: {
        discountPercent: 100,
        initial: '235.00',
        final: '235.00',
      },
    },
  ],
};
