import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  'liveRecording': [{
    'date': '2020-08-15 03:52',
    'sourceUrl': 'https://www.bilibili.com/video/BV1ci4y1g71M',
    'referer': null,
    'imageUrl': 'BV1ci4y1g71M',
    'tagIds': ['liveRecording'],
    'publisher': '露塔大魔王',
    'description': '因为是直播所以会有意义不明的对话，请大家多多包涵~右下可调清晰度，先调高清再调超清可变清晰~\r\n非攻略向~非攻略向~非攻略向~重要的事情说三遍~\r\n微博名：玛露塔大魔王V    直播间地址：https://live.bilibili.com/936585\r\nPS.娱乐主播，玩的不好不喜勿喷~',
    'typeId': 'liveRecording',
    'id': '5',
    'detail': '',
    'title': '【玛露塔】全面战争特洛伊 流程+吐槽（第一天被乱干的UP，比全战三国难啊！）',
    'views': 146475
  }, {
    'date': '2020-08-10 22:43',
    'sourceUrl': 'https://www.bilibili.com/video/BV15p4y1v7BT',
    'referer': null,
    'imageUrl': 'BV15p4y1v7BT',
    'tagIds': ['liveRecording'],
    'publisher': '阿姆西_MC',
    'description': '直接互动的直播传送门：https://www.huya.com/520180\n热门视频推荐：\n爆笑全面战争模拟器：https://www.bilibili.com/video/av65423529\n骑马与砍杀2场均几十杀：https://www.bilibili.com/video/BV11e411s7iE\n全面战争三国陈王刘宠档：https://www.bilibili.com/video/av85940766\n全面战争三国天命张角档：https://www.bilibili.com/video/av84410141\n全面战争三国马腾攻略档：https://www.bilibili.com/video/av53931454\n全面战争三国董卓mod档：https://www.bilibili.com/video/av61069161\n全面战争三国八王之乱司马亮：https://www.bilibili.com/video/av63013626\n\n全面战争战锤2蜥蜴人纳卡伊：https://www.bilibili.com/video/av79322113\n全面战争战锤2帝国远征军档：https://www.bilibili.com/video/av67797326\n全面战争战锤2吸血鬼海岸档：https://www.bilibili.com/video/av35885103\n全面战争战锤2毁天灭地混沌：https://www.bilibili.com/video/av25138841\n\n你想看的任何派系视频攻略，频道里全都有~\n--------------------------------------------------------------------------------------------------------------------------------\n\n大家有什么想看的内容，可以在下方留言\n欢迎订阅哦！！',
    'typeId': 'liveRecording',
    'id': '7',
    'detail': '',
    'title': '《全面战争传奇：特洛伊》堂堂斯巴达王被老婆抛弃！化身绿帽王强势复仇！',
    'views': 298756
  }],
  'strategy': [{
    'date': '2024-05-13 13:38',
    'sourceUrl': 'https://www.bilibili.com/video/BV17b421B7oe',
    'referer': null,
    'imageUrl': 'BV17b421B7oe',
    'tagIds': ['newerTeach'],
    'publisher': 't心疼你的过',
    'description': '阿伽门农白嫖物资技巧 字幕看app自带的吧',
    'typeId': 'strategy',
    'id': '13',
    'detail': '',
    'title': '全战特洛伊阿伽门农小技巧之一直白嫖一直爽',
    'views': 349
  }, {
    'date': '2024-01-12 18:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV16W4y1A7FU',
    'referer': null,
    'imageUrl': 'BV16W4y1A7FU',
    'tagIds': [''],
    'publisher': '娱帅or娱晓帅',
    'description': '《特洛伊：全面战争》\n34个兵种（神话兵种）\n1-刻耳柏洛斯\n2.悲惨阴影\n3-至福乐土射手\n4-至福乐土矛兵大师\n5-巨人之影\n6-勒拿的许德拉\n7-毒液饮者\n8-许德拉弓箭手\n9-许德拉卫士\n10.许德拉祭司\n11.狮鹫元老\n12.小狮鹫\n13.独目人猎手\n14.独目巨人\n15.独目人突袭兵\n16.半马人猎手\n17.半人马弓箭手\n18.半马人哨兵\n19.半人马勇士\n20.半人马先锋\n21.半人马长枪兵\n22.半人马长者\n23.巨人突袭兵\n24.巨人先锋\n25.巨人弓箭兵\n26.巨人矛兵\n27.巨人冠军勇士\n28.独眼巨人\n29.弥诺陶洛斯\n30.地生人\n31.库瑞忒斯\n32.鹰妖哈比\n33.鹰妖恶魔\n34.塞壬',
    'typeId': 'strategy',
    'id': '6',
    'detail': '',
    'title': '【全面战争：特洛伊】所有神话兵种图鉴（娱帅）',
    'views': 10119
  }, {
    'date': '2023-01-04 14:51',
    'sourceUrl': 'https://www.bilibili.com/video/BV1tR4y1m79H',
    'referer': null,
    'imageUrl': 'BV1tR4y1m79H',
    'tagIds': ['liveRecording'],
    'publisher': '赵官家_',
    'description': '特洛伊全面战争特洛伊王子 超远射程的人形马克沁',
    'typeId': 'strategy',
    'id': '12',
    'detail': '',
    'title': '特洛伊全面战争特洛伊王子 超远射程的人形马克沁',
    'views': 5232
  }, {
    'date': '2021-08-07 11:32',
    'sourceUrl': 'https://www.bilibili.com/video/BV1C44y1C7Bm',
    'referer': null,
    'imageUrl': 'BV1C44y1C7Bm',
    'tagIds': [''],
    'publisher': '阿姆西_MC',
    'description': '直接互动传送门：https://www.huya.com/520180\n热门视频推荐：\n鬼谷八荒爆笑修仙记：BV1r5411J7RM\n骑马与砍杀2千人大战场：BV1ef4y1U7ZW\n全面战争三国官渡郑姜档：BV1rK4y1J7qh\n全面战争三国官渡袁绍档：BV1Gb4y1979R\n全面战争三国南蛮孟获档：BV1qC4y1t7WH\n全面战争三国陈王刘宠档：av85940766\n全面战争三国天命张角档：av84410141\n\n全面战争战锤2史上最强地精：BV1DV411k7mj\n全面战争战锤2暮光姐妹档：BV13y4y1B7Jh\n全面战争战锤2帝国远征军档：av67797326\n\n--------------------------------------------------------------------------------------------------------------------------------\n\n大家有什么想看的内容，可以在下方留言\n欢迎订阅 (๑•̀ㅂ•́)و✧',
    'typeId': 'strategy',
    'id': '4',
    'detail': '',
    'title': '【全面战争特洛伊】九头蛇三头犬实力爆炸！最新神话DLC兵种概览！',
    'views': 137376
  }, {
    'date': '2020-08-18 15:34',
    'sourceUrl': 'https://www.bilibili.com/video/BV16p4y1v7jV',
    'referer': null,
    'imageUrl': 'BV16p4y1v7jV',
    'tagIds': ['newerTeach'],
    'publisher': 'Darktp',
    'description': '',
    'typeId': 'strategy',
    'id': '9',
    'detail': '',
    'title': '【热情如光】全面战争特洛伊基础教学说明合集',
    'views': 2142
  }, {
    'date': '2020-08-17 17:25',
    'sourceUrl': 'https://www.bilibili.com/video/BV1nC4y1t7D5',
    'referer': null,
    'imageUrl': 'BV1nC4y1t7D5',
    'tagIds': ['newerTeach'],
    'publisher': '双尾彗星',
    'description': '特洛伊新手入门指南，第1期介绍兵种差异和不同用法',
    'typeId': 'strategy',
    'id': '3',
    'detail': '',
    'title': '《全面战争：特洛伊》入门指南 第1期：兵种分类',
    'views': 43571
  }, {
    'date': '2020-08-12 18:36',
    'sourceUrl': 'https://www.bilibili.com/video/BV1E54y1i7Cg',
    'referer': null,
    'imageUrl': 'BV1E54y1i7Cg',
    'tagIds': ['newerTeach'],
    'publisher': '双尾彗星',
    'description': '《全面战争：特洛伊》特洛伊阵营英雄和势力特色介绍',
    'typeId': 'strategy',
    'id': '11',
    'detail': '',
    'title': '全面战争：特洛伊——特洛伊派系特色',
    'views': 33263
  }, {
    'date': '2020-08-11 20:01',
    'sourceUrl': 'https://www.bilibili.com/video/BV1pf4y197e2',
    'referer': null,
    'imageUrl': 'BV1pf4y197e2',
    'tagIds': ['newerTeach'],
    'publisher': '双尾彗星',
    'description': '《全面战争：特洛伊》希腊阵营英雄和势力特色介绍',
    'typeId': 'strategy',
    'id': '10',
    'detail': '',
    'title': '全面战争：特洛伊——希腊派系特色',
    'views': 43017
  }],
  'backgroundKnowledge': [{
    'date': '2024-04-13 22:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV11E421u7VC',
    'referer': null,
    'imageUrl': 'BV11E421u7VC',
    'tagIds': [''],
    'publisher': '古老游戏玩家',
    'description': '全面战争传奇-特洛伊，开场动画\n\n英文配音',
    'typeId': 'backgroundKnowledge',
    'id': '14',
    'detail': '',
    'title': '[全面战争 · 特洛伊 · 英文配音] 回到2021年，感受那时的震撼',
    'views': 644
  }, {
    'date': '2024-04-13 22:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV13F4m1N7D9',
    'referer': null,
    'imageUrl': 'BV13F4m1N7D9',
    'tagIds': [''],
    'publisher': '古老游戏玩家',
    'description': '全面战争传奇-特洛伊，开场动画\n\n中文配音',
    'typeId': 'backgroundKnowledge',
    'id': '15',
    'detail': '',
    'title': '[全面战争 · 特洛伊 · 中文配音] 回到2021年，感受那时的震撼',
    'views': 937
  }, {
    'date': '2023-10-16 11:01',
    'sourceUrl': 'https://www.bilibili.com/video/BV1VB4y1f7BW',
    'referer': null,
    'imageUrl': 'BV1VB4y1f7BW',
    'tagIds': [''],
    'publisher': '优秀弟',
    'description': '制作不易，跪谢三连',
    'typeId': 'backgroundKnowledge',
    'id': '1',
    'detail': '',
    'title': '全面战争：法老 VS 全面战争：特洛伊，究竟谁更优秀呢？',
    'views': 5508
  }, {
    'date': '2023-01-04 00:43',
    'sourceUrl': 'https://www.bilibili.com/video/BV1M44y197EC',
    'referer': null,
    'imageUrl': 'BV1M44y197EC',
    'tagIds': [''],
    'publisher': 'lujiajunk1',
    'description': '',
    'typeId': 'backgroundKnowledge',
    'id': '8',
    'detail': '',
    'title': '4090全面战争特洛伊两军对冲4k分辨率，帧数流畅',
    'views': 15193
  }, {
    'date': '2020-08-14 15:37',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Av411i7eF',
    'referer': null,
    'imageUrl': 'BV1Av411i7eF',
    'tagIds': [''],
    'publisher': '双尾彗星',
    'description': '《全面战争传奇：特洛伊》游戏测评，讨论游戏的优缺点和特色、为玩家和观众提供建议，在决定是否购买时进行参考\r\n免费领取链接（8月14日21点前有效）：https://www.epicgames.com/store/zh-CN/product/a-total-war-saga-troy/home',
    'typeId': 'backgroundKnowledge',
    'id': '2',
    'detail': '',
    'title': '剁手之前：《全面战争传奇：特洛伊》评测',
    'views': 27932
  }]
};
