import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  talents: [
    {
      date: '',
      sourceUrl: 'assets/htmls/徐丹.html',
      referer: null,
      imageUrl: 'assets/images/avatar/徐丹.jpg',
      tagIds: [''],
      publisher: '34岁 中专/幼师 人力资源专员/助理（3年9个月）',
      description: '在闲鱼上帮宠物店推广，主要宠物猫、宠物狗，会使用PS',
      typeId: '',
      id: '',
      detail: '已视频会议沟通，经营过头条',
      title: '徐丹 XDaning0817',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/李润婷.html',
      referer: null,
      imageUrl: 'assets/images/avatar/李润婷.jpg',
      tagIds: [''],
      publisher:
        '26岁  9年 重庆市九龙坡区麦积职业培训学校 会计与管理 大专 · 非全日制',
      description:
        '拥有新媒体从0-1起号运营+主播自媒体经验，了解新媒体运营工作、具有用户思维；\n' +
        '掌握抖音运营相关技巧，结合标签账号、时事热点把握账号粉丝需求，拥有良好的沟通表达能力及策划能力；',
      typeId: '',
      id: '',
      detail: '',
      title: '李润婷 Lee1998zayn 18324123088',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/蒋艺阳.html',
      referer: null,
      imageUrl: 'assets/images/avatar/蒋艺阳.jpg',
      tagIds: [''],
      publisher: '00后 2024 应届生',
      description: '养猫',
      typeId: '',
      id: '',
      detail: '',
      title: '蒋艺阳 _THE-KIN-IN-CHINA_',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/李娅欣.html',
      referer: null,
      imageUrl: 'assets/images/avatar/李娅欣.jpg',
      tagIds: [''],
      publisher: '34岁  10年以上  本科 ',
      description: '家里有救助动物的',
      typeId: '',
      id: '',
      detail: '',
      title: '李娅欣 lyxin1026',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/郭玉成.html',
      referer: null,
      imageUrl: 'assets/images/avatar/郭玉成.jpg',
      tagIds: [''],
      publisher: '34岁  10年以上  高中',
      description: '在深圳有3年咖啡师经验',
      typeId: '',
      id: '',
      detail: '',
      title: '郭玉成 crackerheiwa',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/覃薏潼.html',
      referer: null,
      imageUrl: 'assets/images/avatar/覃薏潼.jpg',
      tagIds: [''],
      publisher: '24岁 3年 大专',
      description:
        '本人从事运营工作已有2年经验，具备活动策划、帐号运营、文案撰写、图文排版',
      typeId: '',
      id: '',
      detail: '',
      title: '覃薏潼 QYT06040',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/郭丽君.html',
      referer: null,
      imageUrl: 'assets/images/avatar/郭丽君.jpg',
      tagIds: [''],
      publisher: '34岁  10年以上  高中',
      description: '专业，头脑灵活，情商高',
      typeId: '',
      id: '',
      detail: '已视频会议沟通，波西猫宠客服，帮忙出了第一个页面的文字和文本',
      title: '郭丽君 wxid_62dhgdaslj7c22',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/徐娟.html',
      referer: null,
      imageUrl: 'assets/images/avatar/徐娟.jpg',
      tagIds: [''],
      publisher: '35岁  10年以上  本科',
      description: '宠物美容师',
      typeId: '',
      id: '',
      detail:
        '挺有意思的人，已经洗过了400多个狗，喜欢洗狗不喜欢洗猫，考了宠物美容师证，经常在宠物店兼职，但收入不稳定，准备自己开一家宠物店，讲自己的爱好变成事业，住在西丽，后来搬到宝安。',
      title: '徐娟 HongDi2021',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/孙晓帆.html',
      referer: null,
      imageUrl: 'assets/images/avatar/孙晓帆.png',
      tagIds: [''],
      publisher: '38岁  10年以上  大专',
      description: '市场总监 大老板',
      typeId: '',
      id: '',
      detail:
        '孙总，只比我大一岁，听我声音还以为我是年轻人。他的声音有点沙了，应该抽烟喝酒太多，他说自己养过宠物，还有兄弟是这个行业，有宠物货源，甚至有人从外国找狗自己培育。他问我想怎么合作，我跟他讲了想法，他认同宠物行业不错，还抱怨我们这个年代不好，没吃到红利，认同。但我跟他说每个时代其实都有风口行业，房地产->互联网->区块链->短视频->旅游，宠物行业之后，老年人服务/用品以后也会爆发，他可能有香港背景，一定是广东人。他说能提供宠物资料和图片，约我下周（今天是20241204）去他公司聊聊。',
      title: '孙晓帆 lucksunny777',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/朱仪.html',
      referer: null,
      imageUrl: 'assets/images/avatar/朱仪.jpg',
      tagIds: [''],
      publisher: '27岁 2年 大专',
      description: '宠物销售 懂猫 言辞犀利',
      typeId: '',
      id: '',
      detail:
        '这个女生说话非常有警惕性，基本不透露什么信息，她问我懂不懂猫，直接说比我懂猫，那是当然的，言语有一定攻击性，能拉人血压，但是她很有见解，毕业两年的工作都是和猫有关，她先问了我们做什么，怎么推广自己的项目，提出猫活体在网上不好做交易，问我们有没有建立售后系统，说售后很重要，问我知不知道猫销售的过程，售后的细节，我拿狗的细节和她对了一遍，她才透露了一些细节，比如猫基本都有毒，幼猫打了疫苗自带毒，体检合格率低，血统猫开证明也要2000，不过这点我提出不同的客户要求不同，要求的高的价格贵，要求不多的才便宜，她还提出了交易细节问题，怎么进行交易，我说有三种情况，我们提供交易地点，你提供交易地点，或者远程发货，她还提出了违约金和垫付的问题，如果是她找猫舍拿猫，要先垫付，如何交易失败，还要付猫舍违约金。',
      title: '朱仪 j1006799374',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/王总-XCDH91688.html',
      referer: null,
      imageUrl: 'assets/images/avatar/王总-XCDH91688.jpg',
      tagIds: [''],
      publisher: '41岁  10年以上  大专 ',
      description: '宠物用品供应链',
      typeId: '',
      id: '',
      detail:
        '宠物用品供应链，懂策划，了解地推供销，在龙华做宠物用品，说这个行业要全国搞要400个W，不懂线上',
      title: '王总-XCDH91688',
      views: 0,
    },
    {
      date: '',
      sourceUrl: 'assets/htmls/曹海鑫-chx-134.html',
      referer: null,
      imageUrl: 'assets/images/avatar/曹海鑫-chx-134.png',
      tagIds: [''],
      publisher: '26岁  10年  高中',
      description: '宠物美容师',
      typeId: '',
      id: '',
      detail:
        '宠物美容师，2年多经验，接待过上千只猫狗洗护美容，女朋友6年经验，也是这行的，有想法，能提供猫货源、宠物护理服务代喂养',
      title: '曹海鑫-chx-134',
      views: 0,
    },
  ],
};
