import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  Switch_Axe: [
    {
      date: '2025-03-02 15:54',
      sourceUrl: 'https://www.bilibili.com/video/BV1iz9bY7ENx',
      referer: null,
      imageUrl: 'BV1iz9bY7ENx',
      tagIds: [''],
      publisher: '他说他是路人乙',
      description:
        '孩子们，强击瓶GP玩不来！\n属性瓶无脑解！\n催更群：699691423',
      typeId: 'Switch_Axe',
      id: '39',
      detail: '',
      title:
        '【怪猎荒野】玩法简单却有T0强度！霸体无脑解的属性瓶斩斧！爆解伤口流斩斧玩法！',
      views: 26492,
    },
    {
      date: '2021-04-21 19:38',
      sourceUrl: 'https://www.bilibili.com/video/BV1y64y1m7pL',
      referer: null,
      imageUrl: 'BV1y64y1m7pL',
      tagIds: ['clansDescription'],
      publisher: 'GreenteaD綠茶哥',
      description:
        '希望喜欢我视频的朋友三连+关注支持一下吧~\n我是一个喜欢琢磨乐于分享的怪猎爱好者，希望与各位一路同行，也欢迎交流和指导！',
      typeId: 'Switch_Axe',
      id: '17',
      detail: '',
      title: '【怪物猎人 崛起】保姆级斩击斧教学 20分钟从入门到精通',
      views: 177847,
    },
  ],
  Hammer: [
    {
      date: '2025-03-02 23:37',
      sourceUrl: 'https://www.bilibili.com/video/BV1Ju98YoEKg',
      referer: null,
      imageUrl: 'BV1Ju98YoEKg',
      tagIds: [''],
      publisher: '疯猪竟然',
      description: '我感觉抡大锤的我好像脑血栓患者',
      typeId: 'Hammer',
      id: '35',
      detail: '',
      title:
        '怪物猎人 荒野 大锤 新手操作教程 配撞思路 实战演示 纯萌新向，我玩的也不是很明白',
      views: 839,
    },
    {
      date: '2025-02-15 12:00',
      sourceUrl: 'https://www.bilibili.com/video/BV1hmKTe1E2Y',
      referer: null,
      imageUrl: 'BV1hmKTe1E2Y',
      tagIds: ['clansDescription'],
      publisher: '口吃亨利',
      description:
        '时间戳\n0:00 基本招式\n2:42 蓄力招式\n5:26 反击招式\n7:05 弱点攻击\n7:45 跳跃攻击\n8:49 常用连招\n11:21 总复习',
      typeId: 'Hammer',
      id: '10',
      detail: '',
      title:
        '【怪物猎人荒野：大锤详细教学】有点灵活！大风车＋陀螺？尝老衲一棒！附PC指法！',
      views: 15389,
    },
    {
      date: '2019-11-10 20:37',
      sourceUrl: 'https://www.bilibili.com/video/BV1qE411Y7Nb',
      referer: null,
      imageUrl: 'BV1qE411Y7Nb',
      tagIds: ['clansDescription'],
      publisher: '-是的_巴佬-',
      description:
        '有什么关于怪物猎人世界的问题都可以私信问我，乐意帮助每一个热爱这款游戏的人，就算我没玩过的武器也会帮忙研究实用思路和个人的见解！\r\n系列视频只有3集都是我非常有心得的武器\r\n弓箭 av71164446\r\n片手剑 av73375473\r\n大锤 av75247541\r\n冥赤龙后的毕业配装讲解 av80687046',
      typeId: 'Hammer',
      id: '9',
      detail: '',
      title: '【怪物猎人世界】冰原：大锤详细教学【讲先生】最莽实战心得',
      views: 494779,
    },
  ],
  Hunting_Horn: [
    {
      date: '2025-03-04 19:35',
      sourceUrl: 'https://www.bilibili.com/video/BV1rT9nYTEX8',
      referer: null,
      imageUrl: 'BV1rT9nYTEX8',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '[怪物猎人·荒野·狩猎笛乱按] 护凶爪龙\n\n萌新实况\n\n我的游戏站\nhttp://111.230.29.99/',
      typeId: 'Hunting_Horn',
      id: '47',
      detail: '',
      title: '[怪物猎人·荒野·狩猎笛乱按] 护凶爪龙',
      views: 133,
    },
    {
      date: '2025-03-03 11:05',
      sourceUrl: 'https://www.bilibili.com/video/BV1om9vYKEie',
      referer: null,
      imageUrl: 'BV1om9vYKEie',
      tagIds: [''],
      publisher: '猫猫天神玩游戏',
      description: 'youtube',
      typeId: 'Hunting_Horn',
      id: '36',
      detail: '',
      title: '怪物猎人：荒野  狩猎笛使用指南-连招与变化【DS翻译】',
      views: 114,
    },
    {
      date: '2021-06-29 18:00',
      sourceUrl: 'https://www.bilibili.com/video/BV18f4y1b7uy',
      referer: null,
      imageUrl: 'BV18f4y1b7uy',
      tagIds: ['clansDescription'],
      publisher: '慕容牛',
      description: '-',
      typeId: 'Hunting_Horn',
      id: '12',
      detail: '',
      title: 'MHR怪物猎人崛起【狩猎笛】从零到老鸟-新手入门 教程/教学/攻略',
      views: 318356,
    },
    {
      date: '2019-02-24 21:22',
      sourceUrl: 'https://www.bilibili.com/video/BV1ub41187Yd',
      referer: null,
      imageUrl: 'BV1ub41187Yd',
      tagIds: ['clansDescription'],
      publisher: '鹅卵石惊险又刺激',
      description:
        '全武器已经全部更新。另外，吹爆笛子。\n虫棍：av30755245 双刀：av37659035 大剑：av32268708 弓箭：av34669815\n长枪：av33320423 盾斧：av33800973 太刀：av34194749 锤子：av37049102\n斩斧：av32726405 轻弩：av41092031 铳枪：av40512816 重弩：av38805180\n片手：av42399323 笛子：av44603353\n\n1群：619710179 \n2群：668288838 \n3群：839407864\nps群：561468355',
      typeId: 'Hunting_Horn',
      id: '11',
      detail: '',
      title: 'MHW 狩猎笛从入门到精通 教学+装备推荐+实战演示（怪物猎人世界）',
      views: 991614,
    },
  ],
  Lance: [
    {
      date: '2025-03-01 08:40',
      sourceUrl: 'https://www.bilibili.com/video/BV1NxXSY9EBx',
      referer: null,
      imageUrl: 'BV1NxXSY9EBx',
      tagIds: [''],
      publisher: '叫我RHeige',
      description:
        'Discord https://discord.gg/xMBk7br3tP\n【订阅频道】https://www.youtube.com/@RHeige?sub_confirmation=1\n【加入会员】https://www.youtube.com/@RHeige/join\n\n《怪物猎人 荒野》分享这两天玩长枪学到的一些小心得\n\n#怪物猎人荒野 #monsterhunterwilds\n\n合作邮箱：rheigetogether@gmail.com',
      typeId: 'Lance',
      id: '37',
      detail: '',
      title: '《怪物猎人 荒野》分享这两天玩长枪的一些小小心得',
      views: 18993,
    },
    {
      date: '2024-11-04 00:31',
      sourceUrl: 'https://www.bilibili.com/video/BV1KdSmYyE2p',
      referer: null,
      imageUrl: 'BV1KdSmYyE2p',
      tagIds: ['clansDescription'],
      publisher: '叫我RHeige',
      description:
        'Discord https://discord.gg/xMBk7br3tP\n【订阅频道】https://www.youtube.com/@RHeige?sub_confirmation=1\n【加入会员】https://www.youtube.com/@RHeige/join\n\n《魔物猎人荒野》「长枪」玩法教学 | 我心目中最优雅的一把武器\n00:00 教学\n07:45 实战演示\n\n#魔物猎人荒野 #monsterhunterwilds\n\n合作邮箱：rheigetogether@gmail.com',
      typeId: 'Lance',
      id: '14',
      detail: '',
      title: '《怪物猎人荒野》「长枪」玩法教学 | 我心目中最优雅的一把武器',
      views: 23733,
    },
    {
      date: '2020-05-23 22:28',
      sourceUrl: 'https://www.bilibili.com/video/BV1eK4y1t7f9',
      referer: null,
      imageUrl: 'BV1eK4y1t7f9',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '关于基础操作00：52\r\n关于不同防御：05：54\r\n关于防御冲刺：11：16\r\n关于冲刺：16：18\r\n关于派生动作19：27\r\n\r\n那么我们下期再见！~',
      typeId: 'Lance',
      id: '13',
      detail: '',
      title: '【CC】怪物猎人世界武器基础+进阶教学：长枪篇',
      views: 137275,
    },
  ],
  Great_Sword: [
    {
      date: '2025-03-01 18:52',
      sourceUrl: 'https://www.bilibili.com/video/BV18yXXYMEqS',
      referer: null,
      imageUrl: 'BV18yXXYMEqS',
      tagIds: [''],
      publisher: '不老温-龙猎人',
      description:
        '群友东问西问，回答一个问题回答太多，懒了，直接水个教学视频，丢链接就完事儿了哈哈\n刚好还有合适的广告玩一玩看看',
      typeId: 'Great_Sword',
      id: '32',
      detail: '',
      title: '怪物猎人荒野：大剑新手教学（不废话版）',
      views: 28279,
    },
    {
      date: '2023-11-28 06:00',
      sourceUrl: 'https://www.bilibili.com/video/BV1Dw411n7EP',
      referer: null,
      imageUrl: 'BV1Dw411n7EP',
      tagIds: ['clansDescription'],
      publisher: 'Win9zlc',
      description:
        '希望能对你有所帮助\n\n水友群：292447037\n\n感谢水友\n@玩家云 @赤貉 @EUREKA_NANA \n的友情参演',
      typeId: 'Great_Sword',
      id: '2',
      detail: '',
      title: '【MHWI-武器速成】 大剑——你是真正的中流砥柱！',
      views: 398567,
    },
    {
      date: '2020-04-12 15:44',
      sourceUrl: 'https://www.bilibili.com/video/BV16T4y1G7cD',
      referer: null,
      imageUrl: 'BV16T4y1G7cD',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '本期带来大剑的基础+进阶教程，包括一些小技巧与注意事项。关于配装与实战部分我们依然会在往后给出~。大家如果喜欢一定要三连+关注哈！\r\n基础操作：00：49\r\n关于肩撞：04：51\r\n滑坡+高空动作：08：53\r\n派生动作：09：53\r\n\r\n那我们下期再见！',
      typeId: 'Great_Sword',
      id: '1',
      detail: '',
      title: '【CC】怪物猎人武器基础+进阶教学：大剑篇',
      views: 336003,
    },
  ],
  Bow: [
    {
      date: '2025-03-02 19:51',
      sourceUrl: 'https://www.bilibili.com/video/BV1XA9hYSEtV',
      referer: null,
      imageUrl: 'BV1XA9hYSEtV',
      tagIds: [''],
      publisher: '疯猪竟然',
      description:
        '我是菜逼，别喷了，因为我怪猎每代玩的都不是很深，基本就几十小时。虽然玩了这么多年，但是每次玩新作都好像是从0开始玩！你们就当我头一次玩怪猎就行。。。',
      typeId: 'Bow',
      id: '44',
      detail: '',
      title:
        '怪物猎人 荒野 弓 新手向教程  配撞思路 （非完全毕业） 实战演示 输出手法',
      views: 6006,
    },
    {
      date: '2023-08-31 10:00',
      sourceUrl: 'https://www.bilibili.com/video/BV1ih4y1N7Wo',
      referer: null,
      imageUrl: 'BV1ih4y1N7Wo',
      tagIds: ['clansDescription'],
      publisher: '强击瓶大剑',
      description:
        '直播之余陆陆续续做了很久，感觉还是有很多东西没讲到。进阶没有讲得很细，有些东西太抽象很难说明白。不过我觉得都是很有用的东西，也都是我很后面才知道的一些知识。迫于时间没法细细打磨实在抱歉，以后有空会补上配装、技能讲解、竞速相关。好久没认真做视频，技术力方面尽力而为了，麦有点烂，不是很满意。喜欢可以三连加关注一下。',
      typeId: 'Bow',
      id: '23',
      detail: '',
      title: '【MHWI】怪物猎人世界冰原 万场弓箭侠的弓箭教学',
      views: 727741,
    },
    {
      date: '2021-06-18 20:43',
      sourceUrl: 'https://www.bilibili.com/video/BV1vU4y157oy',
      referer: null,
      imageUrl: 'BV1vU4y157oy',
      tagIds: ['clansDescription'],
      publisher: '慕容牛',
      description: '-',
      typeId: 'Bow',
      id: '24',
      detail: '',
      title: 'MHR怪物猎人崛起【弓箭】从零到老鸟-新手入门 教程/教学/攻略',
      views: 712290,
    },
  ],
  practicalTeaching: [
    {
      date: '2025-03-04 08:43',
      sourceUrl: 'https://www.bilibili.com/video/BV1PJ97YaEAD',
      referer: null,
      imageUrl: 'BV1PJ97YaEAD',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '[怪物猎人·荒野] 什么？这样就行了！？\n\n入门级技巧\n\n我的游戏站\nhttp://111.230.29.99/',
      typeId: 'practicalTeaching',
      id: '46',
      detail: '',
      title: '[怪物猎人·荒野] 什么？这样就行了！？',
      views: 125,
    },
    {
      date: '2025-03-02 22:41',
      sourceUrl: 'https://www.bilibili.com/video/BV1Vn98YJEWL',
      referer: null,
      imageUrl: 'BV1Vn98YJEWL',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description: '萌新翻滚平砍流\n\n我的游戏站\nhttp://111.230.29.99/',
      typeId: 'practicalTeaching',
      id: '31',
      detail: '',
      title: '[怪物猎人·荒野] 最终战，无剪辑，新人翻滚平砍流',
      views: 50,
    },
    {
      date: '2025-02-09 13:01',
      sourceUrl: 'https://www.bilibili.com/video/BV1LBNyeWE6f',
      referer: null,
      imageUrl: 'BV1LBNyeWE6f',
      tagIds: [''],
      publisher: 'TeamDarkside',
      description:
        '锁刃龙和太刀的相性很好，所以Gluco给大家带来了这支视频\n\n希望你们喜欢!',
      typeId: 'practicalTeaching',
      id: '28',
      detail: '',
      title: '【怪物猎人荒野】太刀 锁刃龙 7分36秒',
      views: 202973,
    },
  ],
  Insect_Glaive: [
    {
      date: '2025-03-03 11:05',
      sourceUrl: 'https://www.bilibili.com/video/BV1YR9vYhEwy',
      referer: null,
      imageUrl: 'BV1YR9vYhEwy',
      tagIds: [''],
      publisher: '奉闲Wu_Jinn',
      description: '',
      typeId: 'Insect_Glaive',
      id: '41',
      detail: '',
      title: '操虫棍篇 怪物猎人荒野全素材武器衍生制造查询',
      views: 204,
    },
    {
      date: '2020-01-08 12:00',
      sourceUrl: 'https://www.bilibili.com/video/BV1oJ411V7Vi',
      referer: null,
      imageUrl: 'BV1oJ411V7Vi',
      tagIds: ['clansDescription'],
      publisher: '灵音Seki',
      description:
        '历史3个月之久的成果，涵盖了目前操虫棍的大多数要点。\n想说的基本都在视频里了，BGM列表见P3的ed字幕。\n视频形式上分别借鉴了 咕料 YJJ 和 猛男 的片子。\n还有什么问题可以发弹幕写评论。',
      typeId: 'Insect_Glaive',
      id: '19',
      detail: '',
      title:
        '【MHWI】世界+冰原 操虫棍全面教学（基础+进阶+实战 真·从入门到精致）',
      views: 1601369,
    },
  ],
  Sword_and_Shield: [
    {
      date: '2025-02-27 09:41',
      sourceUrl: 'https://www.bilibili.com/video/BV1xUPpeVELe',
      referer: null,
      imageUrl: 'BV1xUPpeVELe',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '[怪物猎人·两分钟教程] 片手剑\n\n我的游戏站\nhttp://111.230.29.99/\n\n正品PS5游戏卡带代购！',
      typeId: 'Sword_and_Shield',
      id: '29',
      detail: '',
      title: '[怪物猎人·两分钟教程] 片手剑',
      views: 766,
    },
    {
      date: '2020-05-01 19:48',
      sourceUrl: 'https://www.bilibili.com/video/BV1vi4y1t7Tu',
      referer: null,
      imageUrl: 'BV1vi4y1t7Tu',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '本期带来久违的片手剑基础+进阶教学~，片手剑小技巧和灵活性都非常不俗，大家如果喜欢本期视频一定要三连+关注哈！~\r\n关于基础操作：00：54\r\n蓄力打击+小升龙：05：23\r\n精准打击+派生动作：10：42\r\n\r\n那么我们下期再见！~',
      typeId: 'Sword_and_Shield',
      id: '4',
      detail: '',
      title: '【CC】怪物猎人世界武器基础+进阶教学：片手剑篇',
      views: 182469,
    },
    {
      date: '2019-02-02 07:12',
      sourceUrl: 'https://www.bilibili.com/video/BV1Xb411k7pS',
      referer: null,
      imageUrl: 'BV1Xb411k7pS',
      tagIds: ['clansDescription'],
      publisher: '鹅卵石惊险又刺激',
      description:
        '喜欢视频的，不妨关注点赞硬币收藏。p2那局运气不错，没演示到什么，但就是快。\n虫棍：av30755245 双刀：av37659035 大剑：av32268708 弓箭：av34669815\n长枪：av33320423 盾斧：av33800973 太刀：av34194749 锤子：av37049102\n斩斧：av32726405 轻弩：av41092031 铳枪：av40512816 重弩：av38805180\n片手：av42399323 笛子：av44603353\n\n1群：619710179 \n2群：668288838 \n3群：839407864\nps群：561468355',
      typeId: 'Sword_and_Shield',
      id: '5',
      detail: '',
      title: 'MHW 片手剑从入门到精通 教学+装备推荐+实战演示（怪物猎人世界）',
      views: 1128270,
    },
  ],
  Heavy_Bowgun: [
    {
      date: '2025-03-02 14:24',
      sourceUrl: 'https://www.bilibili.com/video/BV1qrXfYeEG8',
      referer: null,
      imageUrl: 'BV1qrXfYeEG8',
      tagIds: [''],
      publisher: '绿茶GameLab',
      description:
        '希望喜欢我视频的朋友三连+关注支持一下吧~\n我是一个喜欢琢磨乐于分享的怪猎爱好者，希望与各位一路同行，也欢迎交流和指导！',
      typeId: 'Heavy_Bowgun',
      id: '43',
      detail: '',
      title:
        "【怪物猎人荒野】依然t0！重炮的浪漫 重弩配装路线推荐 | 附上位刺花蜘蛛实战 3''29",
      views: 52242,
    },
    {
      date: '2025-02-16 08:00',
      sourceUrl: 'https://www.bilibili.com/video/BV1iMAKekEk3',
      referer: null,
      imageUrl: 'BV1iMAKekEk3',
      tagIds: ['clansDescription'],
      publisher: '羊角棉苞',
      description: '做完我才发现我写了好几个“这作重弩最大的改动是xxxxx”',
      typeId: 'Heavy_Bowgun',
      id: '21',
      detail: '',
      title:
        '【怪物猎人荒野β测】十分钟带你了解一下眉毛以下截肢重做的荒野重弩！',
      views: 42186,
    },
    {
      date: '2018-12-23 09:52',
      sourceUrl: 'https://www.bilibili.com/video/BV17t411k76H',
      referer: null,
      imageUrl: 'BV17t411k76H',
      tagIds: ['clansDescription'],
      publisher: '鹅卵石惊险又刺激',
      description:
        '虫棍：av30755245 双刀：av37659035 大剑：av32268708 弓箭：av34669815\n长枪：av33320423 盾斧：av33800973 太刀：av34194749 锤子：av37049102\n斩斧：av32726405 轻弩：av41092031 铳枪：av40512816 重弩：av38805180\n片手：av42399323 笛子：av44603353\n\n1群：619710179 \n2群：668288838 \n3群：839407864\nps群：561468355',
      typeId: 'Heavy_Bowgun',
      id: '22',
      detail: '',
      title: 'MHW 重弩从入门到精通 教学+装备推荐+实战演示（怪物猎人世界）',
      views: 1845952,
    },
  ],
  Light_Bowgun: [
    {
      date: '2025-03-03 11:17',
      sourceUrl: 'https://www.bilibili.com/video/BV1vD9vYPE6y',
      referer: null,
      imageUrl: 'BV1vD9vYPE6y',
      tagIds: [''],
      publisher: '奉闲Wu_Jinn',
      description: '',
      typeId: 'Light_Bowgun',
      id: '42',
      detail: '',
      title: '轻弩炮篇 怪物猎人荒野全素材武器衍生制造查询',
      views: 142,
    },
    {
      date: '2019-01-19 07:22',
      sourceUrl: 'https://www.bilibili.com/video/BV1Yt411a7bP',
      referer: null,
      imageUrl: 'BV1Yt411a7bP',
      tagIds: ['clansDescription'],
      publisher: '鹅卵石惊险又刺激',
      description:
        '关注 点赞 硬币 收藏啊，各位。\n虫棍：av30755245 双刀：av37659035 大剑：av32268708 弓箭：av34669815\n长枪：av33320423 盾斧：av33800973 太刀：av34194749 锤子：av37049102\n斩斧：av32726405 轻弩：av41092031 铳枪：av40512816 重弩：av38805180\n片手：av42399323 笛子：av44603353\n\n1群：619710179 \n2群：668288838 \n3群：839407864\nps群：561468355',
      typeId: 'Light_Bowgun',
      id: '20',
      detail: '',
      title: 'MHW 轻弩从入门到精通 教学+装备推荐+实战演示（怪物猎人世界）',
      views: 1506287,
    },
  ],
  Dual_Blades: [
    {
      date: '2025-03-02 12:16',
      sourceUrl: 'https://www.bilibili.com/video/BV13a9FY8E1N',
      referer: null,
      imageUrl: 'BV13a9FY8E1N',
      tagIds: [''],
      publisher: '肉卷大大',
      description:
        '正式开始做荒野的系列攻略，东西需要慢慢测试和实战才能给出相对准确答案，大家别着急。',
      typeId: 'Dual_Blades',
      id: '34',
      detail: '',
      title: '<怪物猎人荒野>双刀基础操作讲解和开荒装备推荐-双剑-MHW-',
      views: 65212,
    },
    {
      date: '2025-02-08 18:37',
      sourceUrl: 'https://www.bilibili.com/video/BV1sFN3e3ECS',
      referer: null,
      imageUrl: 'BV1sFN3e3ECS',
      tagIds: ['clansDescription'],
      publisher: '口吃亨利',
      description: '',
      typeId: 'Dual_Blades',
      id: '6',
      detail: '',
      title:
        '【怪物猎人荒野：双剑详细教学】最推T0新手武器？上手容易！核心机制一次搞懂！',
      views: 31305,
    },
    {
      date: '2023-02-11 18:42',
      sourceUrl: 'https://www.bilibili.com/video/BV1hd4y1J7oa',
      referer: null,
      imageUrl: 'BV1hd4y1J7oa',
      tagIds: ['clansDescription'],
      publisher: '慕容牛',
      description: '随机应变之神器',
      typeId: 'Dual_Blades',
      id: '8',
      detail: '',
      title: 'MHR怪物猎人崛起-曙光【双剑/双刀】新手快速入门教程/教学',
      views: 447311,
    },
    {
      date: '2021-05-11 02:57',
      sourceUrl: 'https://www.bilibili.com/video/BV1S54y157pC',
      referer: null,
      imageUrl: 'BV1S54y157pC',
      tagIds: ['clansDescription'],
      publisher: 'Xkun',
      description:
        '家里出现了一些事情压力非常的大 大晚上的还断网下雨\n也睡不着 反而思路清晰了不少 给大家来做个双刀教学 经常推荐人玩双刀 终于也出个实际了\n感谢大家收看 视频不易记得三连关注 推荐给自己朋友哦！',
      typeId: 'Dual_Blades',
      id: '7',
      detail: '',
      title:
        '【怪物猎人:崛起】双刀/双剑超详细保姆级教学来了!爽到!看完你也当砍王',
      views: 848047,
    },
  ],
  Long_Sword: [
    {
      date: '2025-03-05 17:18',
      sourceUrl: 'https://www.bilibili.com/video/BV1KH9dYyEf2',
      referer: null,
      imageUrl: 'BV1KH9dYyEf2',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '[怪物猎人·荒野·太刀] 11分钟杀煌雷龙，尽力了！\n\n萌新实况\n\n我的游戏站\nhttp://111.230.29.99/',
      typeId: 'Long_Sword',
      id: '48',
      detail: '',
      title: '[怪物猎人·荒野·太刀] 11分钟杀煌雷龙，尽力了！',
      views: 35,
    },
    {
      date: '2025-03-02 10:35',
      sourceUrl: 'https://www.bilibili.com/video/BV1fUXdYwERi',
      referer: null,
      imageUrl: 'BV1fUXdYwERi',
      tagIds: [''],
      publisher: '阿奶26号奶茶铺',
      description:
        '开篇及按键区分 （开始至1:02）\n基础攻击讲解 （1:02至2:02）\n练气槽及气刃等级讲解 （2:02至3:36）\n如何开刃（内含体操,见切,居合）讲解 （3:36至7:06）\n新招：气刃蓄力讲解 （7:06至8:20）\n不常用开刃方法 （8:20至9:04）\n登龙及练气解放无双斩讲解 （9:04至10:26）\n集中模式讲解 （10:26至11:00）\n伤口机制讲解 （11:00至12:00）\n尾声 （12:00至结束） \n\n（免责声明：我并非专精太刀，虽然一测二测环节中几乎全程使用太刀，且世界中太刀使用800场次，但如教学内容有错误还请大家帮我指出）',
      typeId: 'Long_Sword',
      id: '33',
      detail: '',
      title: '【怪猎荒野】太刀保姆级教学！从零开始的狩猎之旅',
      views: 4840,
    },
    {
      date: '2020-03-25 20:43',
      sourceUrl: 'https://www.bilibili.com/video/BV1e7411y7f6',
      referer: null,
      imageUrl: 'BV1e7411y7f6',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '本期视频带来的是太刀的基础教学~关于没有讲解到的特殊收到，居合以及快速上刃我们会在进阶教学中给出~\r\n基础操作：00：48\r\n关于气刃：02：48\r\n关于气刃兜割：07：28\r\n关于看破斩：09：37\r\n如果大家喜欢一定要一键三连+关注~~\r\n我们下期再见！',
      typeId: 'Long_Sword',
      id: '3',
      detail: '',
      title: '【CC】怪物猎人世界武器基础教学系列：太刀篇',
      views: 226706,
    },
  ],
  Gunlance: [
    {
      date: '2025-03-02 23:34',
      sourceUrl: 'https://www.bilibili.com/video/BV1zG98YREBb',
      referer: null,
      imageUrl: 'BV1zG98YREBb',
      tagIds: [''],
      publisher: '极度扭曲的藤子',
      description: '荒野的铳枪是不是有点超模了？这么幸福真的好吗',
      typeId: 'Gunlance',
      id: '38',
      detail: '',
      title: '【MHWilds】没有技巧全是数值！荒野1.0铳枪毕业配装推荐',
      views: 20036,
    },
    {
      date: '2025-02-14 12:28',
      sourceUrl: 'https://www.bilibili.com/video/BV1BUKPeEES5',
      referer: null,
      imageUrl: 'BV1BUKPeEES5',
      tagIds: ['clansDescription'],
      publisher: '口吃亨利',
      description:
        '时间戳\n0:00 铳枪介绍\n1:55 常用连段\n5:24 精准防御\n7:16 弱点攻击\n8:22 总复习',
      typeId: 'Gunlance',
      id: '15',
      detail: '',
      title:
        '《怪物猎人荒野：铳枪详细教学》Double龙杭连弹爽过头！必学强势连段！附PC指法！',
      views: 48713,
    },
    {
      date: '2020-04-15 19:16',
      sourceUrl: 'https://www.bilibili.com/video/BV1s5411x7Sv',
      referer: null,
      imageUrl: 'BV1s5411x7Sv',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '本期带来铳枪基础+进阶教学，其中包括流派与打法的介绍。如果大家喜欢一定要三连+关注哈！\n关于基础操作：01：04\n蓄力炮及龙击炮：07：01\n三大流派及打法10：04\n关于斜坡动作：16：27\n关于起爆龙杭：17：14\n\n那么我们下期再见！~',
      typeId: 'Gunlance',
      id: '16',
      detail: '',
      title: '【CC】怪物猎人世界武器基础+进阶教学：铳枪篇',
      views: 403659,
    },
  ],
  articles: [
    {
      date: '2025-03-03 13:48',
      sourceUrl: 'https://www.bilibili.com/video/BV1fF9vYMEkM',
      referer: null,
      imageUrl: 'BV1fF9vYMEkM',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '[怪物猎人·荒野] 通关锐评\n\n我的游戏站\nhttp://111.230.29.99/',
      typeId: 'articles',
      id: '45',
      detail: '',
      title: '[怪物猎人·荒野] 通关锐评',
      views: 270,
    },
    {
      date: '2025-02-28 17:45',
      sourceUrl: 'https://www.bilibili.com/video/BV1iP9GYTEHA',
      referer: null,
      imageUrl: 'BV1iP9GYTEHA',
      tagIds: [''],
      publisher: '古老游戏玩家',
      description:
        '2月28日，怪物猎人·荒野开盒！PS5 SLIM\n\n卡带之家，我开发的网站：\nhttp://111.230.29.99/\n\n需要正品原封港卡，请私信联系！',
      typeId: 'articles',
      id: '30',
      detail: '',
      title: '2月28日，怪物猎人·荒野开盒！PS5 SLIM',
      views: 198,
    },
    {
      date: '2025-02-24 14:18',
      sourceUrl: 'https://www.bilibili.com/video/BV1iYPsewEDQ',
      referer: null,
      imageUrl: 'BV1iYPsewEDQ',
      tagIds: [''],
      publisher: 'GreenteaD綠茶哥',
      description:
        '希望喜欢我视频的朋友三连+关注支持一下吧~\n我是一个喜欢琢磨乐于分享的怪猎爱好者，希望与各位一路同行，也欢迎交流和指导！',
      typeId: 'articles',
      id: '27',
      detail: '',
      title: '【怪物猎人荒野】助你选择开荒武器！所有改动大盘点+全武器评价',
      views: 18321,
    },
    {
      date: '2025-02-11 12:45',
      sourceUrl: 'https://www.bilibili.com/video/BV1g3NqefEtK',
      referer: null,
      imageUrl: 'BV1g3NqefEtK',
      tagIds: [''],
      publisher: '无限卡皇',
      description: '需要正版新卡，请联系我！\n\n我的网站 http://111.230.29.99/',
      typeId: 'articles',
      id: '25',
      detail: '',
      title: '2025，怪物猎人！萌新如何开始？',
      views: 2448,
    },
    {
      date: '2025-02-06 16:13',
      sourceUrl: 'https://www.bilibili.com/video/BV1SkNJeCEeq',
      referer: null,
      imageUrl: 'BV1SkNJeCEeq',
      tagIds: [''],
      publisher: '无限卡皇',
      description:
        '[卡带价格] 怪物猎人·世界\n\n卡带之家，我开发的网站：\nhttp://111.230.29.99/',
      typeId: 'articles',
      id: '26',
      detail: '',
      title: '[卡带价格] 怪物猎人·世界',
      views: 58,
    },
  ],
  Charge_Blade: [
    {
      date: '2025-03-03 11:55',
      sourceUrl: 'https://www.bilibili.com/video/BV1nJ9iY5Eby',
      referer: null,
      imageUrl: 'BV1nJ9iY5Eby',
      tagIds: [''],
      publisher: '球仔baby',
      description:
        '哈喽我是盾斧小手子球仔！\n欢迎大家在评论区补充套路盾斧的小tips！一起变成盾斧大手子！！',
      typeId: 'Charge_Blade',
      id: '40',
      detail: '',
      title: '手残党也能玩转盾斧！《怪物猎人：荒野》菜鸟变大师，萌新变老登！',
      views: 44,
    },
    {
      date: '2020-03-08 23:07',
      sourceUrl: 'https://www.bilibili.com/video/BV13E411g7mm',
      referer: null,
      imageUrl: 'BV13E411g7mm',
      tagIds: ['clansDescription'],
      publisher: '猎人cc丶',
      description:
        '大家好，我是CC，一位怪物猎人爱好者~\n怪物猎人世界武器基础教学系列将会不定期进行更新，如果你喜欢的话记得三连关注！',
      typeId: 'Charge_Blade',
      id: '18',
      detail: '',
      title: 'CC怪物猎人世界武器基础教学系列：充能斧篇',
      views: 45420,
    },
  ],
};
