import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  'china': [{
    'date': '2024-04-13 02:04',
    'sourceUrl': 'https://www.bilibili.com/video/BV19E421T7VM',
    'referer': null,
    'imageUrl': 'BV19E421T7VM',
    'tagIds': [''],
    'publisher': '君有云美食',
    'description': '-',
    'typeId': 'china',
    'id': '11',
    'detail': '',
    'title': '广东最受欢迎的八道经典名菜，最后一道太绝了',
    'views': 1462036
  }, {
    'date': '2023-10-24 15:45',
    'sourceUrl': 'https://www.bilibili.com/video/BV1ju4y1n7F4',
    'referer': null,
    'imageUrl': 'BV1ju4y1n7F4',
    'tagIds': [''],
    'publisher': '美食爱好者小李子',
    'description': '-',
    'typeId': 'china',
    'id': '16',
    'detail': '',
    'title': '10道湘菜',
    'views': 33151
  }, {
    'date': '2023-08-12 11:30',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Du4y1R7Bj',
    'referer': null,
    'imageUrl': 'BV1Du4y1R7Bj',
    'tagIds': [''],
    'publisher': '真探唐仁杰',
    'description': '又来一家博物馆啊，徽菜博物馆，有点意思。',
    'typeId': 'china',
    'id': '15',
    'detail': '',
    'title': '黄山.徽菜博物馆 厨子探店¥427',
    'views': 1294117
  }, {
    'date': '2022-12-24 12:41',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Qe411c7JL',
    'referer': null,
    'imageUrl': 'BV1Qe411c7JL',
    'tagIds': [''],
    'publisher': '原点科普',
    'description': '盘点浙江十大奇葩美食，当地人为之痴迷，外地人难以下咽',
    'typeId': 'china',
    'id': '14',
    'detail': '',
    'title': '盘点浙江十大奇葩美食，当地人为之痴迷，外地人难以下咽',
    'views': 507294
  }, {
    'date': '2022-11-10 18:34',
    'sourceUrl': 'https://www.bilibili.com/video/BV1kG411w7dH',
    'referer': null,
    'imageUrl': 'BV1kG411w7dH',
    'tagIds': [''],
    'publisher': '黎叔教做菜',
    'description': '麻得安逸，辣得过瘾~',
    'typeId': 'china',
    'id': '10',
    'detail': '',
    'title': '麻辣干香，佐酒下饭！黎叔教你在家做四川特色菜干锅鸡',
    'views': 84671
  }, {
    'date': '2021-10-26 19:29',
    'sourceUrl': 'https://www.bilibili.com/video/BV14r4y117Lw',
    'referer': null,
    'imageUrl': 'BV14r4y117Lw',
    'tagIds': [''],
    'publisher': '江苏菜介绍',
    'description': '视频搬运自互联网',
    'typeId': 'china',
    'id': '13',
    'detail': '',
    'title': '【江苏菜】中国八大菜系之苏菜，苏菜十大名菜，这道菜被誉为天下第一名菜',
    'views': 10806
  }, {
    'date': '2021-09-27 11:50',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Uf4y1w7md',
    'referer': null,
    'imageUrl': 'BV1Uf4y1w7md',
    'tagIds': [''],
    'publisher': '师父和我做鲁菜',
    'description': '师父陈宗明，鲁菜老厨师，我，视频拍摄者大伟，没团队。\n2021年4月底，一个工作多年的老社畜辞去工作，租下一个小院，经过3个月的烈日酷暑的装修后，本畜和师父开始拍摄系列鲁菜。\n原因是我在工作中，发现我们传统的饮食文化正在慢慢的消失，这种消失却是因为时代的浮夸……在这个以大龙虾帝王蟹、辛辣刺激为美的时代，传统烹饪中口味核心的技艺正在逐渐被遗忘，而诸多教做菜的也八仙过海，各显神通，其中很多可能连烧菜和扒菜的味型都分不清楚……\n我并不是针对谁，我只是想拍下我师父和鲁菜，这代表了传统烹饪的一角。',
    'typeId': 'china',
    'id': '9',
    'detail': '',
    'title': '10大经典鲁菜系列⑩【糖醋鲤鱼】，一道我师父沿袭传统又加以改良的菜品之一。',
    'views': 1854565
  }, {
    'date': '2020-11-06 17:26',
    'sourceUrl': 'https://www.bilibili.com/video/BV1PV411174z',
    'referer': null,
    'imageUrl': 'BV1PV411174z',
    'tagIds': [''],
    'publisher': '大师的菜',
    'description': '历时三天才能完成的名菜佛跳墙，一口汤下去居然黏住了嘴巴！',
    'typeId': 'china',
    'id': '12',
    'detail': '',
    'title': '【大师的菜·佛跳墙】天下第一硬菜，18种食材，历时3天，佛跳墙的神话被完整记录！',
    'views': 552902
  }, {
    'date': '2020-08-16 18:26',
    'sourceUrl': 'https://www.bilibili.com/video/BV11V411U7dF',
    'referer': null,
    'imageUrl': 'BV11V411U7dF',
    'tagIds': [''],
    'publisher': '超子美食',
    'description': '青椒炒肉丝，先炒青椒还是肉？很多人都做错了，大厨教你正确做法',
    'typeId': 'china',
    'id': '2',
    'detail': '',
    'title': '青椒炒肉丝，先炒肉还是青椒，很多人都没弄对，难怪做出来不好吃',
    'views': 59945
  }],
  'arabic': [{
    'date': '2022-08-23 11:00',
    'sourceUrl': 'https://www.bilibili.com/video/BV1EW4y187ur',
    'referer': null,
    'imageUrl': 'BV1EW4y187ur',
    'tagIds': [''],
    'publisher': '这个老爸有点帅',
    'description': '你好朋友，在乌兹别克斯坦你永远不会挨饿，或者说你永远不会为找不到美食而发愁，因为我们有NARYN、PILAF、JIZ BIZ与MASTAVA菜谱，它们被认为是非常美味的乌兹别克斯坦美食，我们将在本期视频中向您展示如何准备这些美食，也就是如何制作抓饭，炸鸡，和烹饪牛肉，如果你喜欢本期视频，请给我一键三连',
    'typeId': 'arabic',
    'id': '3',
    'detail': '',
    'title': '【地方美食】抓饭，炸鸡与牛肉食谱｜独特的乌兹别克斯坦美食',
    'views': 5259
  }],
  'southeastAsia': [{
    'date': '2024-04-11 10:38',
    'sourceUrl': 'https://www.bilibili.com/video/BV1vx421S7Q7',
    'referer': null,
    'imageUrl': 'BV1vx421S7Q7',
    'tagIds': [''],
    'publisher': '爱吃的俊河',
    'description': '',
    'typeId': 'southeastAsia',
    'id': '4',
    'detail': '',
    'title': '500 份！ 炒饭 ！ 马来西亚夜市',
    'views': 7779
  }, {
    'date': '2023-09-16 23:04',
    'sourceUrl': 'https://www.bilibili.com/video/BV1B8411q7sQ',
    'referer': null,
    'imageUrl': 'BV1B8411q7sQ',
    'tagIds': [''],
    'publisher': 'RSL寰球美食',
    'description': '',
    'typeId': 'southeastAsia',
    'id': '5',
    'detail': '',
    'title': '马来西亚美食|来到槟城必吃的十大街头美食',
    'views': 19976
  }],
  'europe': [{
    'date': '2023-06-26 11:46',
    'sourceUrl': 'https://www.bilibili.com/video/BV1314y127yU',
    'referer': null,
    'imageUrl': 'BV1314y127yU',
    'tagIds': [''],
    'publisher': '钓鱼名场面',
    'description': '十大法国美食',
    'typeId': 'europe',
    'id': '6',
    'detail': '',
    'title': '【top10】十大法国美食',
    'views': 2767
  }],
  'america': [{
    'date': '2024-05-25 10:18',
    'sourceUrl': 'https://www.bilibili.com/video/BV1pm421T7Qz',
    'referer': null,
    'imageUrl': 'BV1pm421T7Qz',
    'tagIds': [''],
    'publisher': '海之链2024',
    'description': '巴西美食',
    'typeId': 'america',
    'id': '7',
    'detail': '',
    'title': '巴西十大美食',
    'views': 661
  }, {
    'date': '2023-01-07 11:49',
    'sourceUrl': 'https://www.bilibili.com/video/BV1W84y1a7KV',
    'referer': null,
    'imageUrl': 'BV1W84y1a7KV',
    'tagIds': [''],
    'publisher': '三明治大王Owen',
    'description': 'The Ultimate Burrito',
    'typeId': 'america',
    'id': '8',
    'detail': '',
    'title': '终极墨西哥卷饼',
    'views': 133593
  }]
};
