import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  'liveRecording': [{
    'date': '2021-06-06 09:30',
    'sourceUrl': 'https://www.bilibili.com/video/BV1wU4y1j7RG',
    'referer': null,
    'imageUrl': 'BV1wU4y1j7RG',
    'tagIds': [''],
    'publisher': '哔哩瞬',
    'description': '最近开始研究一下全战历代的系列机制，所以顺手打了一点点战报，由于年代久远，仅做机制熟悉参考使用，欢迎大家三连。',
    'typeId': 'liveRecording',
    'id': '3',
    'detail': '',
    'title': '【史前游戏系列】中世纪1全面战争——复古维拜占庭复兴第一期',
    'views': 4041
  }, {
    'date': '2021-04-25 09:30',
    'sourceUrl': 'https://www.bilibili.com/video/BV1DK4y1o71T',
    'referer': null,
    'imageUrl': 'BV1DK4y1o71T',
    'tagIds': [''],
    'publisher': '哔哩瞬',
    'description': '最近开始研究一下全战历代的系列机制，所以顺手打了一点点战报，由于年代久远，仅做机制熟悉参考使用，欢迎大家三连。',
    'typeId': 'liveRecording',
    'id': '5',
    'detail': '',
    'title': '【史前游戏系列】中世纪1全面战争——复古维京入侵撒克逊战报第一期',
    'views': 1323
  }, {
    'date': '2020-11-29 09:30',
    'sourceUrl': 'https://www.bilibili.com/video/BV14a411F7FY',
    'referer': null,
    'imageUrl': 'BV14a411F7FY',
    'tagIds': [''],
    'publisher': '哔哩瞬',
    'description': '这场战斗在中世纪1相比中世纪2在军队配置上还原度更高了一些，将左翼右翼两个军团做了出来，然而老AI却不会坚守阵地，开场就出现乱走的情况，实属可惜。',
    'typeId': 'liveRecording',
    'id': '4',
    'detail': '',
    'title': '【史前游戏系列】中世纪1全面战争历史战役——黑斯廷斯战役',
    'views': 2654
  }, {
    'date': '2020-08-02 09:30',
    'sourceUrl': 'https://www.bilibili.com/video/BV1nA411Y7c3',
    'referer': null,
    'imageUrl': 'BV1nA411Y7c3',
    'tagIds': [''],
    'publisher': '哔哩瞬',
    'description': '带来一期大家一直期待的中世纪1，中世纪1相比之前的幕府可以说难度更大，需要更加巧妙的战术通关。',
    'typeId': 'liveRecording',
    'id': '7',
    'detail': '',
    'title': '【史前游戏系列】中世纪1全面战争历史战役——班诺克本战役',
    'views': 3196
  }],
  'strategy': [{
    'date': '2024-05-18 14:52',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Nf42117gx',
    'referer': null,
    'imageUrl': 'BV1Nf42117gx',
    'tagIds': [''],
    'publisher': '古老游戏玩家',
    'description': '[全面战争 · 中世纪] 新手教学篇 - 跟我入门',
    'typeId': 'strategy',
    'id': '1',
    'detail': '',
    'title': '[全面战争 · 中世纪] 新手教学篇 - 跟我入门',
    'views': 313
  }, {
    'date': '2023-07-27 22:29',
    'sourceUrl': 'https://www.bilibili.com/video/BV1eh4y1y7z5',
    'referer': null,
    'imageUrl': 'BV1eh4y1y7z5',
    'tagIds': [''],
    'publisher': '步行帝国骑士',
    'description': 'YouTube.com\n如何在Windows 10上运行中世纪1。dxwnd和我的设定。我甚至在炫耀的同时改进了我的配置。https://sourceforge.net/projects/dxwnd/',
    'typeId': 'strategy',
    'id': '8',
    'detail': '',
    'title': '如何在2023年运行中世纪1',
    'views': 225
  }, {
    'date': '2023-07-12 07:46',
    'sourceUrl': 'https://www.bilibili.com/video/BV1K94y1B7HF',
    'referer': null,
    'imageUrl': 'BV1K94y1B7HF',
    'tagIds': [''],
    'publisher': '步行帝国骑士',
    'description': 'YouTube.com\n展示中世纪1的天气系统如何运作',
    'typeId': 'strategy',
    'id': '9',
    'detail': '',
    'title': '中世纪1的动态天气（20年前的全战）',
    'views': 860
  }],
  'backgroundKnowledge': [{
    'date': '2024-03-30 21:38',
    'sourceUrl': 'https://www.bilibili.com/video/BV1Qm411k7A7',
    'referer': null,
    'imageUrl': 'BV1Qm411k7A7',
    'tagIds': [''],
    'publisher': '古老游戏玩家',
    'description': '第二代全面战争，震撼开场动画',
    'typeId': 'backgroundKnowledge',
    'id': '2',
    'detail': '',
    'title': '[全面战争 · 中世纪] 回到2003年，感受那时的震撼',
    'views': 4869
  }, {
    'date': '2022-01-31 13:05',
    'sourceUrl': 'https://www.bilibili.com/video/BV1SP4y1N7eq',
    'referer': null,
    'imageUrl': 'BV1SP4y1N7eq',
    'tagIds': [''],
    'publisher': '近卫掷弹骑兵官',
    'description': '欧陆到了14世纪开启了经济复兴，意大利、低地国家和北德城市都出现了人口激增和城市政治派性抬头，这些城市将被迫转向商业城镇联盟，以维持其自治权，而其中最有代表性的就是北德意志的汉萨同盟以及瑞士各城市组织起来的瑞士邦联。我们在该视频中将分析中世纪城邦是如何在几个世纪中发展起来的',
    'typeId': 'backgroundKnowledge',
    'id': '6',
    'detail': '',
    'title': '【中世纪/全面战争】中世纪的商业城镇是如何发展，以及他们是如何保护自身独立地位于封建贵族和君主之外的kings and generals',
    'views': 1729
  }]
};
