import { IArticleMap } from '@w-monorepo/interfaces';

export const ARTICLES_MAP: IArticleMap = {
  new: [
    {
      date: '2024-05-21 18:00',
      sourceUrl: 'https://www.bilibili.com/video/BV11m421K7un',
      referer: null,
      imageUrl: 'BV11m421K7un',
      tagIds: [],
      publisher: '极客GeekEarvin',
      description:
        '交流群：339369935\n一名热爱游戏的玩家\n喜欢的话记得点赞投币关注支持下！\n您的鼓励对我十分重要，感谢！\n游戏评测与视频解说作者\n空闲不多尽力更新\n水平有限请多关照',
      typeId: 'new',
      id: '3',
      detail: '',
      title: '六月新游戏推荐&购买指南【极客盘点】',
      views: 692,
    },
    {
      date: '2024-05-20 17:01',
      sourceUrl: 'https://www.bilibili.com/video/BV1JT421S74Q',
      referer: null,
      imageUrl: 'BV1JT421S74Q',
      tagIds: [],
      publisher: '里红尘',
      description: '2024年6月新游戏',
      typeId: 'new',
      id: '1',
      detail: '',
      title: '【六月新游推荐】黄金树幽影！6月值得期待的七款新游戏介绍',
      views: 8792,
    },
    {
      date: '2024-05-15 12:10',
      sourceUrl: 'https://www.bilibili.com/video/BV1u1421B7j8',
      referer: null,
      imageUrl: 'BV1u1421B7j8',
      tagIds: [],
      publisher: '楠枫Studio',
      description: '2024年6月新游戏推荐',
      typeId: 'new',
      id: '4',
      detail: '',
      title: '【2024年6月新游戏推荐】年度DLC真神降临、老任继续搞重置',
      views: 103770,
    },
  ],
  freeDemo: [
    {
      date: null,
      sourceUrl: 'https://store.steampowered.com/app/2821800',
      referer: null,
      imageUrl: '2821800',
      tagIds: [],
      publisher: 'Hungry Couch Games',
      description:
        '{"short_description": "欢迎来到《钻核公司》，在这里，企业贪婪与战略性星球开采相互交织！在管理工人、研究尖端技术并抵御外星人攻击的同时，向星球的核心钻探。你会选择追求效率而冒险牺牲工人的安全，还是注重防御来确保生存呢？", "price_overview": {}}',
      typeId: 'freeDemo',
      id: '51',
      detail: '',
      title: '钻核公司 (Drill Core)',
      views: 0,
    },
    {
      date: null,
      sourceUrl: 'https://store.steampowered.com/app/837880',
      referer: null,
      imageUrl: '837880',
      tagIds: [],
      publisher: 'Happy Volcano',
      description:
        '{"short_description": "《狂野泊车™》是一款绝无仅有的竞赛游戏，以考验玩家的泊车技术为终极目标。这里多姿多彩却也饱含技巧和难度。加入这个不断发展演化的泊车模拟器，向世界发起挑战，展现您的独家泊车秘技吧！", "price_overview": {"currency": "CNY", "initial": 7600, "final": 760, "discount_percent": 90, "initial_formatted": "¥ 76.00", "final_formatted": "¥ 7.60"}}',
      typeId: 'freeDemo',
      id: '52',
      detail: '',
      title: '狂野泊车 / You Suck at Parking®',
      views: 0,
    },
    {
      date: null,
      sourceUrl: 'https://store.steampowered.com/app/2185030',
      referer: null,
      imageUrl: '2185030',
      tagIds: [],
      publisher: 'Abyte Entertainment',
      description:
        '{"short_description": "在大家最喜欢的讨价还价大亨游戏《当铺人生》的新作中，接受充满挑战性的流浪商人任务，并成为一代传奇吧！", "price_overview": {}}',
      typeId: 'freeDemo',
      id: '53',
      detail: '',
      title: '当铺人生传奇',
      views: 0,
    },
  ],
  discount: [
    {
      date: '2024-06-18',
      sourceUrl: 'https://store.steampowered.com/app/1364780',
      referer: null,
      imageUrl: '1364780',
      tagIds: [],
      publisher: 'CAPCOM Co., Ltd.',
      description:
        '{"short_description": "系列最新作《Street Fighter 6》将于2023年6月2日发售！ 本作以RE ENGINE开发，并由系列前所未有的大型模式“环球游历”、“斗技战场”以及“格斗中心”构成。新的“Street Fighter”和前所未有的全新体验正在等待着你的到来。", "price_overview": {"currency": "CNY", "initial": 29800, "final": 14900, "discount_percent": 50, "initial_formatted": "¥ 298.00", "final_formatted": "¥ 149.00"}}',
      typeId: 'discount',
      id: '50',
      detail: '',
      title: 'Street Fighter 6',
      views: 0,
    },
    {
      date: '2024-06-14',
      sourceUrl: 'https://store.steampowered.com/app/1315610',
      referer: null,
      imageUrl: '1315610',
      tagIds: [],
      publisher: 'Carry Castle',
      description:
        '{"short_description": "《Source of Madness》是一款横向卷轴roguelite黑暗风格动作游戏，背景设在灵感源自洛夫克拉夫特神话，以AI机器学习驱动，由程序自动生成的扭曲世界。你将成为一位新来的教徒，踏上一段噩梦般的旅程。", "price_overview": {"currency": "CNY", "initial": 7000, "final": 2450, "discount_percent": 65, "initial_formatted": "¥ 70.00", "final_formatted": "¥ 24.50"}}',
      typeId: 'discount',
      id: '40',
      detail: '',
      title: 'Source of Madness',
      views: 0,
    },
    {
      date: '2024-06-13',
      sourceUrl: 'https://store.steampowered.com/app/1956800',
      referer: null,
      imageUrl: '1956800',
      tagIds: [],
      publisher: 'White Star Studio',
      description:
        '{"short_description": "公元960年，赵宋王朝建立，社会百废待兴。作为新上任的知县大人，你将带领百姓开荒建城，振兴百业，打造盛世繁华！ 车水马龙，士农工商，看那酒楼茶坊遍布大街小巷，勾栏瓦舍唱尽人世悲欢。然而歌舞升平背后则是暗藏的危机。面对党阀相争、外敌入侵等重重困境，在时代的洪流中你将如何抉择？", "price_overview": {"currency": "CNY", "initial": 6800, "final": 5100, "discount_percent": 25, "initial_formatted": "¥ 68.00", "final_formatted": "¥ 51.00"}}',
      typeId: 'discount',
      id: '38',
      detail: '',
      title: '满庭芳：宋上繁华',
      views: 0,
    },
    {
      date: '2024-06-12',
      sourceUrl: 'https://store.steampowered.com/app/1176470',
      referer: null,
      imageUrl: '1176470',
      tagIds: [],
      publisher: 'Pavonis Interactive',
      description:
        '{"short_description": "神秘的外星力量逼近太阳系，不知是敌是友。关于外星人的动机和应对方法，众说纷纭。你将参与各方力量的角逐，率领你的阵营，在太阳系中实现你的愿景。《地球不屈》是宏大的硬科幻战略游戏： 战斗符合牛顿物理学；太阳系的比例高度准确；允许自定义飞船设计；战略情况因为公转而充满复杂的变化。", "price_overview": {"currency": "CNY", "initial": 14900, "final": 11175, "discount_percent": 25, "initial_formatted": "¥ 149.00", "final_formatted": "¥ 111.75"}}',
      typeId: 'discount',
      id: '33',
      detail: '',
      title: '地球不屈 Terra Invicta',
      views: 0,
    },
    {
      date: '2024-06-12',
      sourceUrl: 'https://store.steampowered.com/app/1336490',
      referer: null,
      imageUrl: '1336490',
      tagIds: [],
      publisher: 'Eremite Games',
      description:
        '{"short_description": "这是一款黑暗奇幻风格的城市建造模拟游戏，在游戏中，你将在席卷而来的灾变之中担起重建文明的使命。作为女王的总督，你将带领人类、海狸、狐狸、蜥蜴以及鸟身女怪们开拓荒野，为文明的遗民们构筑崭新的未来。", "price_overview": {"currency": "CNY", "initial": 9900, "final": 6435, "discount_percent": 35, "initial_formatted": "¥ 99.00", "final_formatted": "¥ 64.35"}}',
      typeId: 'discount',
      id: '44',
      detail: '',
      title: '风暴之城 Against the Storm',
      views: 0,
    },
    {
      date: '2024-06-11',
      sourceUrl: 'https://store.steampowered.com/app/275850',
      referer: null,
      imageUrl: '275850',
      tagIds: [],
      publisher: 'Hello Games',
      description:
        '{"short_description": "《无人深空》是一款打破边界的科幻游戏，通过创新的随机生成技术，打造了一个无尽宇宙供玩家自由探索，玩家可以穿越星际、挖掘未知星球、建立基地并与神秘外星生物共生，每个探险家都将书写属于自己的宇宙传奇。", "price_overview": {"currency": "CNY", "initial": 17500, "final": 8750, "discount_percent": 50, "initial_formatted": "¥ 175.00", "final_formatted": "¥ 87.50"}}',
      typeId: 'discount',
      id: '31',
      detail: '',
      title: "No Man's Sky 无人深空",
      views: 0,
    },
    {
      date: '2024-06-11',
      sourceUrl: 'https://store.steampowered.com/app/990630',
      referer: null,
      imageUrl: '990630',
      tagIds: [],
      publisher: 'Hello Games',
      description:
        '{"short_description": "《最后的篝火》（Last Campfire）是一个以冒险为主题的游戏，游戏主线描述的是一个迷失的余烬角色被困在一个谜题世界，为了寻找家园的定义和曲折返乡之旅的故事", "price_overview": {"currency": "CNY", "initial": 5800, "final": 580, "discount_percent": 90, "initial_formatted": "¥ 58.00", "final_formatted": "¥ 5.80"}}',
      typeId: 'discount',
      id: '34',
      detail: '',
      title: 'The Last Campfire',
      views: 0,
    },
    {
      date: '2024-06-11',
      sourceUrl: 'https://store.steampowered.com/app/376300',
      referer: null,
      imageUrl: '376300',
      tagIds: [],
      publisher: 'Arc System Works',
      description:
        '{"short_description": "久等了。终于来啦！［罪恶装备未知次元-征兆］在Steam上隆重登场！", "price_overview": {"currency": "CNY", "initial": 8800, "final": 880, "discount_percent": 90, "initial_formatted": "¥ 88.00", "final_formatted": "¥ 8.80"}}',
      typeId: 'discount',
      id: '37',
      detail: '',
      title: 'GUILTY GEAR Xrd -SIGN-',
      views: 0,
    },
    {
      date: '2024-06-11',
      sourceUrl: 'https://store.steampowered.com/app/990080',
      referer: null,
      imageUrl: '990080',
      tagIds: [],
      publisher: 'Avalanche Software',
      description:
        '{"short_description": "《霍格沃茨之遗》是一款沉浸式开放世界动作角色扮演游戏。这回，你将在魔法世界中扮演“你自己”，亲手书写属于自己的传奇。", "price_overview": {"currency": "CNY", "initial": 38400, "final": 19200, "discount_percent": 50, "initial_formatted": "¥ 384.00", "final_formatted": "¥ 192.00"}}',
      typeId: 'discount',
      id: '41',
      detail: '',
      title: '霍格沃茨之遗',
      views: 0,
    },
    {
      date: '2024-06-11',
      sourceUrl: 'https://store.steampowered.com/app/1161580',
      referer: null,
      imageUrl: '1161580',
      tagIds: [],
      publisher: 'Blackbird Interactive',
      description:
        '{"short_description": "利用最先进的废物回收科技切割太空船，回收高价值材料。升级装备，接取更加有利可图的合同，偿还您对LYNX Corp的数十亿信用债务！", "price_overview": {"currency": "CNY", "initial": 14900, "final": 5960, "discount_percent": 60, "initial_formatted": "¥ 149.00", "final_formatted": "¥ 59.60"}}',
      typeId: 'discount',
      id: '49',
      detail: '',
      title: '迷走深空：碎舰师',
      views: 0,
    },
    {
      date: '2024-06-08',
      sourceUrl: 'https://store.steampowered.com/app/951440',
      referer: null,
      imageUrl: '951440',
      tagIds: [],
      publisher: 'Volcanoid',
      description:
        '{"short_description": "《火山岛》是一个第一人称、基地建设的生存游戏，游戏设定在人和技术共存的蒸汽朋克时代。你需要探索火山岛，操控巨大的钻井船并且在由机械生物引发的火山喷发中生存下来。", "price_overview": {"currency": "CNY", "initial": 7000, "final": 4900, "discount_percent": 30, "initial_formatted": "¥ 70.00", "final_formatted": "¥ 49.00"}}',
      typeId: 'discount',
      id: '48',
      detail: '',
      title: 'Volcanoids',
      views: 0,
    },
    {
      date: '2024-06-07',
      sourceUrl: 'https://store.steampowered.com/app/1824220',
      referer: null,
      imageUrl: '1824220',
      tagIds: [],
      publisher: 'Torn Banner Studios',
      description:
        '{"short_description": "回到终极中世纪战场。 《Chivalry 2》是一款灵感源于中世纪战争史诗电影的多人第一人称砍杀游戏。玩家们将体验到这个时代的所有标志性时刻——从剑刃交锋，到燃烧箭雨，再到铺天盖地的城堡围攻等等，应有尽有。", "price_overview": {"currency": "CNY", "initial": 11600, "final": 3828, "discount_percent": 67, "initial_formatted": "¥ 116.00", "final_formatted": "¥ 38.28"}}',
      typeId: 'discount',
      id: '46',
      detail: '',
      title: 'Chivalry 2',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/211820',
      referer: null,
      imageUrl: '211820',
      tagIds: [],
      publisher: 'Chucklefish',
      description:
        '{"short_description": "You’ve fled your home, only to find yourself lost in space with a damaged ship. Your only option is to beam down to the planet below, repair your ship and set off to explore the universe...", "price_overview": {"currency": "CNY", "initial": 5800, "final": 2320, "discount_percent": 60, "initial_formatted": "¥ 58.00", "final_formatted": "¥ 23.20"}}',
      typeId: 'discount',
      id: '32',
      detail: '',
      title: 'Starbound',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/1868140',
      referer: null,
      imageUrl: '1868140',
      tagIds: [],
      publisher: 'MINTROCKET',
      description:
        '{"short_description": "欢迎访问以神秘蓝洞为背景的海洋冒险游戏【潜水员戴夫 DAVE THE DIVER】。 白天在美丽的大海里打鱼，晚上经营寿司店赚钱。 伴随着个性强的同事们的故事展开的海底谜团。神秘又崭新的乐趣正在等着您！", "price_overview": {"currency": "CNY", "initial": 8000, "final": 6000, "discount_percent": 25, "initial_formatted": "¥ 80.00", "final_formatted": "¥ 60.00"}}',
      typeId: 'discount',
      id: '30',
      detail: '',
      title: '潜水员戴夫 DAVE THE DIVER',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/468920',
      referer: null,
      imageUrl: '468920',
      tagIds: [],
      publisher: 'Pancake Games',
      description:
        '{"short_description": "Bored of waiting for a bite? Would you like to catch some fish? You\'re lucky - in Ultimate Fishing Simulator, fish bite like crazy! Spinning, float fishing, ground fishing and more!", "price_overview": {"currency": "CNY", "initial": 7600, "final": 912, "discount_percent": 88, "initial_formatted": "¥ 76.00", "final_formatted": "¥ 9.12"}}',
      typeId: 'discount',
      id: '35',
      detail: '',
      title: '终极钓鱼模拟器',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/1951230',
      referer: null,
      imageUrl: '1951230',
      tagIds: [],
      publisher: 'Cosy Computer',
      description:
        '{"short_description": "闯进这个闹腾的街机游戏大快朵颐，实现自己终极的负鼠梦想。不论单人还是本地合作，都可以放开肚皮吃，只要不被抓住就好。", "price_overview": {"currency": "CNY", "initial": 2900, "final": 1740, "discount_percent": 40, "initial_formatted": "¥ 29.00", "final_formatted": "¥ 17.40"}}',
      typeId: 'discount',
      id: '36',
      detail: '',
      title: '负鼠闹翻天',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/233860',
      referer: null,
      imageUrl: '233860',
      tagIds: [],
      publisher: 'Lo-Fi Games',
      description:
        '{"short_description": "一款以自由行动小分队为基础的角色扮演RPG类游戏。专注于开放式的沙盒游戏功能而非线性故事。选择成为商人、小偷、反叛者、军阀、冒险者、农民、奴隶或是食人族的牙祭。探索新设备，锻造新装备。", "price_overview": {"currency": "CNY", "initial": 9000, "final": 3600, "discount_percent": 60, "initial_formatted": "¥ 90.00", "final_formatted": "¥ 36.00"}}',
      typeId: 'discount',
      id: '43',
      detail: '',
      title: 'Kenshi',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/1210320',
      referer: null,
      imageUrl: '1210320',
      tagIds: [],
      publisher: 'niceplay games',
      description:
        '{"short_description": "在《药剂工艺：炼金模拟器》中，你将扮演一个炼金术士，并使用各种工具和原料来调制药剂。你将掌控药剂商店的方方面面：发明新配方、吸引顾客、并尽情地做实验。不过请记住：整个小镇都指望着你。", "price_overview": {"currency": "CNY", "initial": 7600, "final": 3420, "discount_percent": 55, "initial_formatted": "¥ 76.00", "final_formatted": "¥ 34.20"}}',
      typeId: 'discount',
      id: '45',
      detail: '',
      title: '药剂工艺：炼金模拟器',
      views: 0,
    },
    {
      date: '2024-06-04',
      sourceUrl: 'https://store.steampowered.com/app/387990',
      referer: null,
      imageUrl: '387990',
      tagIds: [],
      publisher: 'Axolot Games',
      description:
        '{"short_description": "Enter the creative paradise of Scrap Mechanic! Build fantastic machines, go on adventures with your friends and defend against waves of evil Farmbots in this imaginative multiplayer survival sandbox. With Scrap Mechanic’s powerful creation tools you can engineer your own adventures!", "price_overview": {"currency": "CNY", "initial": 6800, "final": 4556, "discount_percent": 33, "initial_formatted": "¥ 68.00", "final_formatted": "¥ 45.56"}}',
      typeId: 'discount',
      id: '47',
      detail: '',
      title: 'Scrap Mechanic',
      views: 0,
    },
    {
      date: '2024-06-03',
      sourceUrl: 'https://store.steampowered.com/app/346010',
      referer: null,
      imageUrl: '346010',
      tagIds: [],
      publisher: 'Spiderling Studios',
      description:
        '{"short_description": "Besiege是一款物理建造游戏，你需要在此建造战争机器以破坏安宁的村庄、歼灭军队并摧毁城堡。在战役中征服敌人，或与好友一起加入多人游戏，展开小规模战斗！", "price_overview": {"currency": "CNY", "initial": 5800, "final": 1450, "discount_percent": 75, "initial_formatted": "¥ 58.00", "final_formatted": "¥ 14.50"}}',
      typeId: 'discount',
      id: '42',
      detail: '',
      title: '围攻',
      views: 0,
    },
  ],
  newest: [
    {
      date: '2024-06-07',
      sourceUrl: 'https://store.steampowered.com/app/2646460',
      referer: null,
      imageUrl: '2646460',
      tagIds: [],
      publisher: 'CampFire Studio',
      description:
        '{"short_description": "你从一场致命的原始祭祀仪式中侥幸逃脱，在逃亡途中意外得到来自远古的神秘面甲。面甲所蕴含超出想象的知识和力量击碎了你的见识与信仰，但也重新给了你生存和斗争下去的希望。面对严酷自然的挑战生存下去，探索这个世界的文明和神秘面甲背后的真相……", "price_overview": {"currency": "CNY", "initial": 10800, "final": 9720, "discount_percent": 10, "initial_formatted": "¥ 108.00", "final_formatted": "¥ 97.20"}}',
      typeId: 'newest',
      id: '39',
      detail: '',
      title: '灵魂面甲(Soulmask)',
      views: 0,
    },
  ],
};
